# Generated by Django 3.0.10 on 2021-11-20 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_budget', '0006_masterparameters_deleted'),
        ('main', '0007_manejodeviaticos_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPerformingAssetsCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='Estado', default=True, null=True)),
                ('identifier', models.CharField(blank=True, db_column='Identificador', max_length=150, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_update_non_performing_assets_category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroActivosFijosCat',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='NonPerformingAssetsScenario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('correlative', models.CharField(blank=True, db_column='Correlativo', max_length=50, null=True)),
                ('comment', models.CharField(blank=True, db_column='Comentario', max_length=500, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='Estado', default=True, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Eliminado', default=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('parameter_id', models.ForeignKey(db_column='ParametroId', on_delete=django.db.models.deletion.DO_NOTHING, to='master_budget.MasterParameters')),
                ('period_id', models.ForeignKey(blank=True, db_column='PeriodoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Periodo')),
                ('updated_by', models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_upd_non_performing_assets_scenario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroActivosFijosEsc',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='NonPerformingAssetsXCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('total_accumulated_balance', models.DecimalField(blank=True, db_column='SaldoTotalAcumulado', decimal_places=2, default=0, max_digits=23, null=True)),
                ('accumulated_depreciation_balance', models.DecimalField(blank=True, db_column='SaldoDepreciacionAcumulado', decimal_places=2, default=0, max_digits=23, null=True)),
                ('depreciation_balance', models.DecimalField(blank=True, db_column='SaldoDepreciacion', decimal_places=2, default=0, max_digits=23, null=True)),
                ('total_net_balance', models.DecimalField(blank=True, db_column='SaldoTotalNeto', decimal_places=2, default=0, max_digits=23, null=True)),
                ('amount_increases', models.DecimalField(blank=True, db_column='MontoAumento', decimal_places=2, default=0, max_digits=23, null=True)),
                ('amount_decreases', models.DecimalField(blank=True, db_column='MontoDisminucion', decimal_places=2, default=0, max_digits=23, null=True)),
                ('new_total_balance', models.DecimalField(blank=True, db_column='NuevoSaldoTotal', decimal_places=2, default=0, max_digits=23, null=True)),
                ('new_accumulated_depreciation_balance', models.DecimalField(blank=True, db_column='NuevoSaldoDepreciacionAcumulado', decimal_places=2, default=0, max_digits=23, null=True)),
                ('category_id', models.ForeignKey(blank=True, db_column='CategoriaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='non_performing_assets.NonPerformingAssetsCategory')),
                ('scenario_id', models.ForeignKey(blank=True, db_column='EscenarioId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='non_performing_assets.NonPerformingAssetsScenario')),
            ],
            options={
                'db_table': 'pptoMaestroActivosFijosXCategoria',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='BudgetedNonProductiveAssets',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('budgeted_asset_id', models.ForeignKey(blank=True, db_column='ActivoPresupuestadoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Detallexpresupuestoinversion')),
                ('scenario_id', models.ForeignKey(blank=True, db_column='EscenarioId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='non_performing_assets.NonPerformingAssetsScenario')),
            ],
            options={
                'db_table': 'pptoMaestroActivosFijosPresupuestados',
                'default_permissions': [],
            },
        ),
    ]
