# Generated by Django 3.0.10 on 2021-11-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_performing_assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonperformingassetsxcategory',
            name='new_accumulated_depreciation_balance',
        ),
        migrations.AddField(
            model_name='nonperformingassetsxcategory',
            name='new_depreciation_balance',
            field=models.DecimalField(blank=True, db_column='NuevoSaldoDepreciacion', decimal_places=2, default=0, max_digits=23, null=True),
        ),
    ]
