# Generated by Django 3.0.10 on 2021-11-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_performing_assets', '0003_nonperformingassetscategorymapaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonperformingassetsxcategory',
            name='comment_decreases',
            field=models.CharField(blank=True, db_column='ComentarioDisminucion', default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nonperformingassetsxcategory',
            name='comment_increases',
            field=models.CharField(blank=True, db_column='ComentarioAumento', default='', max_length=200, null=True),
        ),
    ]
