# Generated by Django 3.0.10 on 2021-11-25 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_budget', '0006_masterparameters_deleted'),
        ('main', '0007_manejodeviaticos_categoria'),
        ('non_performing_assets', '0004_auto_20211121_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherAssetsCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='Estado', default=True, null=True)),
                ('identifier', models.CharField(blank=True, db_column='Identificador', max_length=150, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_update_others_assets_category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroOtrosActivosCat',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='OtherAssetsScenario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('correlative', models.CharField(blank=True, db_column='Correlativo', max_length=50, null=True)),
                ('comment', models.CharField(blank=True, db_column='Comentario', max_length=500, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='Estado', default=True, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Eliminado', default=False, null=True)),
                ('category_id', models.ForeignKey(db_column='CategoryId', on_delete=django.db.models.deletion.DO_NOTHING, to='non_performing_assets.OtherAssetsCategory')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('parameter_id', models.ForeignKey(db_column='ParametroId', on_delete=django.db.models.deletion.DO_NOTHING, to='master_budget.MasterParameters')),
                ('period_id', models.ForeignKey(blank=True, db_column='PeriodoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Periodo')),
                ('updated_by', models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_upd_others_assets_scenario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroOtrosActivosEsc',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='OtherAssets',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('category', models.IntegerField(blank=True, db_column='Categoria', null=True)),
                ('previous_balance', models.DecimalField(blank=True, db_column='SaldoAnterior', decimal_places=2, default=0, max_digits=23, null=True)),
                ('criteria', models.IntegerField(blank=True, choices=[(1, 'Mismo Valor'), (3, 'Porcentaje de Aumento'), (4, 'Porcentaje de Disminución'), (5, 'Nuevo Valor')], db_column='Criterio', null=True)),
                ('percentage', models.FloatField(blank=True, db_column='Procentaje', default=0, null=True)),
                ('new_balance', models.DecimalField(blank=True, db_column='NuevoSaldo', decimal_places=2, default=0, max_digits=23, null=True)),
                ('scenario_id', models.ForeignKey(blank=True, db_column='EscenarioId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='non_performing_assets.OtherAssetsScenario')),
            ],
            options={
                'db_table': 'pptoMaestroOtrosActivos',
                'default_permissions': [],
            },
        ),
    ]
