# Generated by Django 3.0.10 on 2021-11-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_performing_assets', '0006_auto_20211126_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherassets',
            name='category_name',
            field=models.CharField(blank=True, db_column='CategoriaNombre', max_length=150, null=True),
        ),
    ]
