# Generated by Django 3.0.10 on 2021-11-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_performing_assets', '0007_otherassets_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherassets',
            name='comment',
            field=models.CharField(blank=True, db_column='Comentario', default='', max_length=200, null=True),
        ),
    ]
