# Generated by Django 3.0.10 on 2021-11-26 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('non_performing_assets', '0008_otherassets_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherassets',
            name='category_id',
            field=models.ForeignKey(blank=True, db_column='CategoriaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='non_performing_assets.OtherAssetsCategory'),
        ),
        migrations.AlterField(
            model_name='otherassets',
            name='criteria',
            field=models.IntegerField(blank=True, choices=[(1, 'Mismo Valor'), (2, 'Porcentaje de Aumento'), (3, 'Porcentaje de Disminución'), (4, 'Nuevo Valor')], db_column='Criterio', null=True),
        ),
    ]
