# Generated by Django 3.0.10 on 2022-06-21 13:22

import apps.master_budget.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_performing_assets', '0011_auto_20220616_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherassets',
            name='percentage_april',
            field=models.FloatField(blank=True, db_column='PorcentajeAbr', default=0, null=True, validators=[apps.master_budget.models.is_percentage]),
        ),
        migrations.AlterField(
            model_name='otherassets',
            name='percentage_august',
            field=models.FloatField(blank=True, db_column='PorcentajeAgo', default=0, null=True, validators=[apps.master_budget.models.is_percentage]),
        ),
        migrations.AlterField(
            model_name='otherassets',
            name='percentage_december',
            field=models.FloatField(blank=True, db_column='PorcentajeDic', default=0, null=True, validators=[apps.master_budget.models.is_percentage]),
        ),
        migrations.AlterField(
            model_name='otherassets',
            name='percentage_february',
            field=models.FloatField(blank=True, db_column='PorcentajeFeb', default=0, null=True, validators=[apps.master_budget.models.is_percentage]),
        ),
        migrations.AlterField(
            model_name='otherassets',
            name='percentage_january',
            field=models.FloatField(blank=True, db_column='PorcentajeEne', default=0, null=True, validators=[apps.master_budget.models.is_percentage]),
        ),
        migrations.AlterField(
            model_name='otherassets',
            name='percentage_july',
            field=models.FloatField(blank=True, db_column='PorcentajeJul', default=0, null=True, validators=[apps.master_budget.models.is_percentage]),
        ),
        migrations.AlterField(
            model_name='otherassets',
            name='percentage_june',
            field=models.FloatField(blank=True, db_column='PorcentajeJun', default=0, null=True, validators=[apps.master_budget.models.is_percentage]),
        ),
        migrations.AlterField(
            model_name='otherassets',
            name='percentage_march',
            field=models.FloatField(blank=True, db_column='PorcentajeMar', default=0, null=True, validators=[apps.master_budget.models.is_percentage]),
        ),
        migrations.AlterField(
            model_name='otherassets',
            name='percentage_may',
            field=models.FloatField(blank=True, db_column='PorcentajeMay', default=0, null=True, validators=[apps.master_budget.models.is_percentage]),
        ),
        migrations.AlterField(
            model_name='otherassets',
            name='percentage_november',
            field=models.FloatField(blank=True, db_column='PorcentajeNov', default=0, null=True, validators=[apps.master_budget.models.is_percentage]),
        ),
        migrations.AlterField(
            model_name='otherassets',
            name='percentage_october',
            field=models.FloatField(blank=True, db_column='PorcentajeOct', default=0, null=True, validators=[apps.master_budget.models.is_percentage]),
        ),
        migrations.AlterField(
            model_name='otherassets',
            name='percentage_september',
            field=models.FloatField(blank=True, db_column='PorcentajeSep', default=0, null=True, validators=[apps.master_budget.models.is_percentage]),
        ),
    ]
