# Generated by Django 3.0.10 on 2022-07-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_performing_assets', '0012_auto_20220621_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherassets',
            name='percentage_april',
        ),
        migrations.RemoveField(
            model_name='otherassets',
            name='percentage_august',
        ),
        migrations.RemoveField(
            model_name='otherassets',
            name='percentage_december',
        ),
        migrations.RemoveField(
            model_name='otherassets',
            name='percentage_february',
        ),
        migrations.RemoveField(
            model_name='otherassets',
            name='percentage_january',
        ),
        migrations.RemoveField(
            model_name='otherassets',
            name='percentage_july',
        ),
        migrations.RemoveField(
            model_name='otherassets',
            name='percentage_june',
        ),
        migrations.RemoveField(
            model_name='otherassets',
            name='percentage_march',
        ),
        migrations.RemoveField(
            model_name='otherassets',
            name='percentage_may',
        ),
        migrations.RemoveField(
            model_name='otherassets',
            name='percentage_november',
        ),
        migrations.RemoveField(
            model_name='otherassets',
            name='percentage_october',
        ),
        migrations.RemoveField(
            model_name='otherassets',
            name='percentage_september',
        ),
        migrations.AddField(
            model_name='otherassets',
            name='increases_april',
            field=models.DecimalField(blank=True, db_column='AumentoAbr', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='otherassets',
            name='increases_august',
            field=models.DecimalField(blank=True, db_column='AumentoAgo', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='otherassets',
            name='increases_december',
            field=models.DecimalField(blank=True, db_column='AumentoDic', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='otherassets',
            name='increases_february',
            field=models.DecimalField(blank=True, db_column='AumentoFeb', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='otherassets',
            name='increases_january',
            field=models.DecimalField(blank=True, db_column='AumentoEne', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='otherassets',
            name='increases_july',
            field=models.DecimalField(blank=True, db_column='AumentoJul', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='otherassets',
            name='increases_june',
            field=models.DecimalField(blank=True, db_column='AumentoJun', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='otherassets',
            name='increases_march',
            field=models.DecimalField(blank=True, db_column='AumentoMar', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='otherassets',
            name='increases_may',
            field=models.DecimalField(blank=True, db_column='AumentoMay', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='otherassets',
            name='increases_november',
            field=models.DecimalField(blank=True, db_column='AumentoNov', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='otherassets',
            name='increases_october',
            field=models.DecimalField(blank=True, db_column='AumentoOct', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='otherassets',
            name='increases_september',
            field=models.DecimalField(blank=True, db_column='AumentoSep', decimal_places=2, default=0, max_digits=23, null=True),
        ),
    ]
