# Generated by Django 3.0.10 on 2022-07-23 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_performing_assets', '0013_auto_20220714_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonperformingassetsxcategory',
            name='month_decreases',
            field=models.IntegerField(blank=True, db_column='MesesDisminucion', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='nonperformingassetsxcategory',
            name='month_increases',
            field=models.IntegerField(blank=True, db_column='MesesAumento', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
