# Generated by Django 3.0.10 on 2021-10-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterparameters',
            name='is_active',
            field=models.BooleanField(blank=True, db_column='Estado', default=False, null=True),
        ),
    ]
