# Generated by Django 3.0.10 on 2021-10-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_budget', '0003_auto_20211006_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanportfoliocategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loanportfoliocategory',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='LoanPortfolio',
        ),
        migrations.DeleteModel(
            name='LoanPortfolioCategory',
        ),
    ]
