# Generated by Django 3.0.10 on 2021-10-12 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_budget', '0004_auto_20211007_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterparameters',
            options={'default_permissions': [], 'ordering': ('period_id', '-date_base')},
        ),
        migrations.AlterField(
            model_name='masterparameters',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterparameters',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[('', '-- Seleccione Estado --'), (True, 'Activo'), (False, 'Inactivo')], db_column='Estado', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='masterparameters',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_update_parameter', to=settings.AUTH_USER_MODEL),
        ),
    ]
