# Generated by Django 3.0.10 on 2021-10-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_budget', '0005_auto_20211012_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterparameters',
            name='deleted',
            field=models.BooleanField(blank=True, db_column='Eliminado', default=False, null=True),
        ),
    ]
