# Generated by Django 3.0.10 on 2021-12-13 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_manejodeviaticos_categoria'),
        ('master_budget', '0006_masterparameters_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogLossesEarnings',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('I', 'Ingresos'), ('P', 'Perdidas')], db_column='Tipo', max_length=1, null=True)),
                ('level_one', models.CharField(blank=True, db_column='Nivel1', max_length=200, null=True)),
                ('level_two', models.CharField(blank=True, db_column='Nivel2', max_length=200, null=True)),
                ('level_three', models.CharField(blank=True, db_column='Nivel3', max_length=200, null=True)),
                ('level_four', models.CharField(blank=True, db_column='Nivel4', max_length=200, null=True)),
                ('order', models.IntegerField(blank=True, db_column='Orden', null=True)),
                ('period_id', models.ForeignKey(db_column='PeriodoId', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Periodo')),
            ],
            options={
                'db_table': 'pptoMaestroPerdidasGananciasCatalogo',
                'ordering': ('period_id', 'type', 'order'),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='LossesEarningsComplementaryProjection',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('month', models.IntegerField(blank=True, choices=[('', '-- Seleccione Mes --'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], db_column='Mes', null=True)),
                ('amount', models.DecimalField(blank=True, db_column='Saldo', decimal_places=2, default=0, max_digits=23, null=True)),
                ('category_id', models.ForeignKey(db_column='CategoriaId', on_delete=django.db.models.deletion.DO_NOTHING, to='master_budget.CatalogLossesEarnings')),
            ],
            options={
                'db_table': 'pptoMaestroPerdidasGananciasProyeccionComplementaria',
                'ordering': ('category_id', '-month'),
                'default_permissions': [],
            },
        ),
    ]
