# Generated by Django 3.0.10 on 2021-12-14 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_manejodeviaticos_categoria'),
        ('master_budget', '0007_cataloglossesearnings_lossesearningscomplementaryprojection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cataloglossesearnings',
            options={'default_permissions': [], 'ordering': ('type', 'order')},
        ),
        migrations.RemoveField(
            model_name='cataloglossesearnings',
            name='period_id',
        ),
        migrations.AddField(
            model_name='lossesearningscomplementaryprojection',
            name='period_id',
            field=models.ForeignKey(blank=True, db_column='PeriodoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Periodo'),
        ),
    ]
