# Generated by Django 3.0.10 on 2022-01-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_budget', '0009_cataloglossesearnings_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurplusDistribution',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pptoMaestroDistribucionExcedentes',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='SurplusDistributionCategory',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pptoMaestroDistribucionExcedentesCategoria',
                'default_permissions': [],
            },
        ),
    ]
