# Generated by Django 3.0.10 on 2022-03-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_budget', '0012_globalgoaldetail_globalgoalperiod_goal_subsidiarygoaldetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalgoalperiod',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='globalgoalperiod',
            name='period_id',
        ),
        migrations.RemoveField(
            model_name='globalgoalperiod',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='subsidiarygoaldetail',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='subsidiarygoaldetail',
            name='id_global_goal_period',
        ),
        migrations.RemoveField(
            model_name='subsidiarygoaldetail',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='GlobalGoalDetail',
        ),
        migrations.DeleteModel(
            name='GlobalGoalPeriod',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='SubsidiaryGoalDetail',
        ),
    ]
