# Generated by Django 3.0.10 on 2022-08-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_budget', '0013_auto_20220304_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurplusDistribution',
        ),
        migrations.DeleteModel(
            name='SurplusDistributionCategory',
        ),
    ]
