# Generated by Django 3.0.10 on 2021-10-07 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPortfolioCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='Estado', default=True, null=True)),
                ('identifier', models.CharField(blank=True, db_column='Identificador', max_length=50, null=True)),
                ('created_by', models.ForeignKey(db_column='CreadoPor', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='ActualizadoPor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_update_loan_portfolio_category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroCartCredCategoria',
                'default_permissions': [],
            },
        ),
    ]
