# Generated by Django 3.0.10 on 2021-10-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_manejodeviaticos_categoria'),
        ('master_budget', '0004_auto_20211007_1346'),
        ('loan_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPortfolioScenario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('category_id', models.ForeignKey(db_column='CategoriaId', on_delete=django.db.models.deletion.DO_NOTHING, to='loan_portfolio.LoanPortfolioCategory')),
                ('parameter_id', models.ForeignKey(db_column='ParametroId', on_delete=django.db.models.deletion.DO_NOTHING, to='master_budget.MasterParameters')),
                ('period_id', models.ForeignKey(db_column='PeriodoId', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Periodo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
