# Generated by Django 3.0.10 on 2021-10-09 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan_portfolio', '0002_loanportfolioscenario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanportfolioscenario',
            options={'default_permissions': []},
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='annual_growth_amount',
            field=models.DecimalField(blank=True, db_column='MontoCrecimientoAnual', decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='annual_growth_percentage',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoAnual', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='base_amount',
            field=models.DecimalField(blank=True, db_column='MontoBase', decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='comment',
            field=models.CharField(blank=True, db_column='Comentario', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='correlative',
            field=models.CharField(blank=True, db_column='Correlativo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='growth_percentage_april',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoAbr', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='growth_percentage_august',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoAgo', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='growth_percentage_december',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoDic', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='growth_percentage_february',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoFeb', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='growth_percentage_january',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoEne', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='growth_percentage_july',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoJul', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='growth_percentage_june',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoJun', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='growth_percentage_march',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoMar', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='growth_percentage_may',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoMay', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='growth_percentage_november',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoNov', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='growth_percentage_october',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoOct', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='growth_percentage_september',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoSep', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='is_active',
            field=models.BooleanField(blank=True, db_column='Estado', default=True, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_april',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraAbr', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_august',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraAgo', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_december',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraDic', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_february',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraFeb', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_january',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraEne', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_july',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraJul', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_june',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraJun', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_march',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraMar', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_may',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraMay', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_november',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraNov', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_october',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraOct', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_september',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraSep', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='rate_april',
            field=models.FloatField(blank=True, db_column='TasaAbr', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='rate_august',
            field=models.FloatField(blank=True, db_column='TasaAgo', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='rate_december',
            field=models.FloatField(blank=True, db_column='TasaDic', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='rate_february',
            field=models.FloatField(blank=True, db_column='TasaFeb', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='rate_january',
            field=models.FloatField(blank=True, db_column='TasaEne', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='rate_july',
            field=models.FloatField(blank=True, db_column='TasaJul', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='rate_june',
            field=models.FloatField(blank=True, db_column='TasaJun', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='rate_march',
            field=models.FloatField(blank=True, db_column='TasaMar', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='rate_may',
            field=models.FloatField(blank=True, db_column='TasaMay', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='rate_november',
            field=models.FloatField(blank=True, db_column='TasaNov', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='rate_october',
            field=models.FloatField(blank=True, db_column='TasaOct', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='rate_september',
            field=models.FloatField(blank=True, db_column='TasaSep', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='term_april',
            field=models.FloatField(blank=True, db_column='TermAbr', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='term_august',
            field=models.FloatField(blank=True, db_column='TermAgo', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='term_december',
            field=models.FloatField(blank=True, db_column='TermDic', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='term_february',
            field=models.FloatField(blank=True, db_column='TermFeb', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='term_january',
            field=models.FloatField(blank=True, db_column='TermEne', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='term_july',
            field=models.FloatField(blank=True, db_column='TermJul', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='term_june',
            field=models.FloatField(blank=True, db_column='TermJun', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='term_march',
            field=models.FloatField(blank=True, db_column='TermMar', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='term_may',
            field=models.FloatField(blank=True, db_column='TermMay', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='term_november',
            field=models.FloatField(blank=True, db_column='TermNov', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='term_october',
            field=models.FloatField(blank=True, db_column='TermOct', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='term_september',
            field=models.FloatField(blank=True, db_column='TermSep', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_upd_loan_portfolio_scenario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='loanportfoliocategory',
            table='pptoMaestroCarteraCredCat',
        ),
        migrations.AlterModelTable(
            name='loanportfolioscenario',
            table='pptoMaestroCarteraCredEsc',
        ),
    ]
