# Generated by Django 3.0.10 on 2021-10-09 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan_portfolio', '0003_auto_20211009_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='commission_percentage_april',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionAbr', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='commission_percentage_august',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionAgo', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='commission_percentage_december',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionDic', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='commission_percentage_february',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionFeb', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='commission_percentage_january',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionEne', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='commission_percentage_july',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionJul', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='commission_percentage_june',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionJun', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='commission_percentage_march',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionMar', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='commission_percentage_may',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionMay', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='commission_percentage_november',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionNov', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='commission_percentage_october',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionOct', null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='commission_percentage_september',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionSep', null=True),
        ),
        migrations.CreateModel(
            name='LoanPortfolio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('month', models.IntegerField(blank=True, choices=[('', '-- Seleccione Mes --'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], db_column='Mes', null=True)),
                ('amount_initial', models.DecimalField(blank=True, db_column='MontoInicial', decimal_places=2, max_digits=23, null=True)),
                ('percent_growth', models.FloatField(blank=True, db_column='PorcentajeCrecimiento', null=True)),
                ('amount_growth', models.DecimalField(blank=True, db_column='MontoCrecimiento', decimal_places=2, max_digits=23, null=True)),
                ('new_amount', models.DecimalField(blank=True, db_column='MontoNuevo', decimal_places=2, max_digits=23, null=True)),
                ('rate', models.FloatField(blank=True, db_column='Tasa', null=True)),
                ('term', models.IntegerField(blank=True, db_column='Plazo', null=True)),
                ('level_quota', models.DecimalField(blank=True, db_column='CuotaNivelada', decimal_places=2, max_digits=23, null=True)),
                ('total_interest', models.DecimalField(blank=True, db_column='InteresesTotales', decimal_places=2, max_digits=23, null=True)),
                ('principal_payments', models.DecimalField(blank=True, db_column='PagosCapital', decimal_places=2, max_digits=23, null=True)),
                ('percentage_arrears', models.FloatField(blank=True, db_column='PorcentajeMora', null=True)),
                ('amount_arrears', models.DecimalField(blank=True, db_column='MontoMora', decimal_places=2, max_digits=23, null=True)),
                ('default_interest', models.DecimalField(blank=True, db_column='InteresesMoratorios', decimal_places=2, max_digits=23, null=True)),
                ('commission_percentage', models.FloatField(blank=True, db_column='PorcentajeComision', null=True)),
                ('commission_amount', models.DecimalField(blank=True, db_column='MontoComision', decimal_places=2, max_digits=23, null=True)),
                ('correlative', models.CharField(blank=True, db_column='Correlativo', max_length=50, null=True)),
                ('comment', models.CharField(blank=True, db_column='Comentario', max_length=500, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='Estado', default=True, null=True)),
                ('created_by', models.ForeignKey(db_column='CreadoPor', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('scenario_id', models.ForeignKey(db_column='CategoriaId', on_delete=django.db.models.deletion.DO_NOTHING, to='loan_portfolio.LoanPortfolioScenario')),
                ('updated_by', models.ForeignKey(db_column='ActualizadoPor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_upd_loan_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroCarteraCred',
                'default_permissions': [],
            },
        ),
    ]
