# Generated by Django 3.0.10 on 2021-10-09 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_portfolio', '0004_auto_20211009_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanportfolio',
            name='scenario_id',
            field=models.ForeignKey(db_column='EscenarioId', on_delete=django.db.models.deletion.DO_NOTHING, to='loan_portfolio.LoanPortfolioScenario'),
        ),
    ]
