# Generated by Django 3.0.10 on 2021-10-11 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_manejodeviaticos_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_budget', '0004_auto_20211007_1346'),
        ('loan_portfolio', '0006_auto_20211009_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanportfolio',
            name='correlative',
        ),
        migrations.RemoveField(
            model_name='loanportfolio',
            name='is_active',
        ),
        migrations.CreateModel(
            name='FinancialInvestmentsScenario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('increases_january', models.DecimalField(blank=True, db_column='AumentoEne', decimal_places=2, max_digits=23, null=True)),
                ('increases_february', models.DecimalField(blank=True, db_column='AumentoFeb', decimal_places=2, max_digits=23, null=True)),
                ('increases_march', models.DecimalField(blank=True, db_column='AumentoMar', decimal_places=2, max_digits=23, null=True)),
                ('increases_april', models.DecimalField(blank=True, db_column='AumentoAbr', decimal_places=2, max_digits=23, null=True)),
                ('increases_may', models.DecimalField(blank=True, db_column='AumentoMay', decimal_places=2, max_digits=23, null=True)),
                ('increases_june', models.DecimalField(blank=True, db_column='AumentoJun', decimal_places=2, max_digits=23, null=True)),
                ('increases_july', models.DecimalField(blank=True, db_column='AumentoJul', decimal_places=2, max_digits=23, null=True)),
                ('increases_august', models.DecimalField(blank=True, db_column='AumentoAgo', decimal_places=2, max_digits=23, null=True)),
                ('increases_september', models.DecimalField(blank=True, db_column='AumentoSep', decimal_places=2, max_digits=23, null=True)),
                ('increases_october', models.DecimalField(blank=True, db_column='AumentoOct', decimal_places=2, max_digits=23, null=True)),
                ('increases_november', models.DecimalField(blank=True, db_column='AumentoNov', decimal_places=2, max_digits=23, null=True)),
                ('increases_december', models.DecimalField(blank=True, db_column='AumentoDic', decimal_places=2, max_digits=23, null=True)),
                ('decreases_january', models.DecimalField(blank=True, db_column='DisminucionesEne', decimal_places=2, max_digits=23, null=True)),
                ('decreases_february', models.DecimalField(blank=True, db_column='DisminucionesFeb', decimal_places=2, max_digits=23, null=True)),
                ('decreases_march', models.DecimalField(blank=True, db_column='DisminucionesMar', decimal_places=2, max_digits=23, null=True)),
                ('decreases_april', models.DecimalField(blank=True, db_column='DisminucionesAbr', decimal_places=2, max_digits=23, null=True)),
                ('decreases_may', models.DecimalField(blank=True, db_column='DisminucionesMay', decimal_places=2, max_digits=23, null=True)),
                ('decreases_june', models.DecimalField(blank=True, db_column='DisminucionesJun', decimal_places=2, max_digits=23, null=True)),
                ('decreases_july', models.DecimalField(blank=True, db_column='DisminucionesJul', decimal_places=2, max_digits=23, null=True)),
                ('decreases_august', models.DecimalField(blank=True, db_column='DisminucionesAgo', decimal_places=2, max_digits=23, null=True)),
                ('decreases_september', models.DecimalField(blank=True, db_column='DisminucionesSep', decimal_places=2, max_digits=23, null=True)),
                ('decreases_october', models.DecimalField(blank=True, db_column='DisminucionesOct', decimal_places=2, max_digits=23, null=True)),
                ('decreases_november', models.DecimalField(blank=True, db_column='DisminucionesNov', decimal_places=2, max_digits=23, null=True)),
                ('decreases_december', models.DecimalField(blank=True, db_column='DisminucionesDic', decimal_places=2, max_digits=23, null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('correlative', models.CharField(blank=True, db_column='Correlativo', max_length=50, null=True)),
                ('comment', models.CharField(blank=True, db_column='Comentario', max_length=500, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='Estado', default=True, null=True)),
                ('category_id', models.ForeignKey(db_column='CategoriaId', on_delete=django.db.models.deletion.DO_NOTHING, to='loan_portfolio.LoanPortfolioCategory')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('parameter_id', models.ForeignKey(db_column='ParametroId', on_delete=django.db.models.deletion.DO_NOTHING, to='master_budget.MasterParameters')),
                ('period_id', models.ForeignKey(db_column='PeriodoId', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Periodo')),
                ('updated_by', models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_upd_financial_investment_scenario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroInversionesFinEsc',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='FinancialInvestmentsCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='Estado', default=True, null=True)),
                ('identifier', models.CharField(blank=True, db_column='Identificador', max_length=50, null=True)),
                ('created_by', models.ForeignKey(db_column='CreadoPor', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='ActualizadoPor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_update_financial_investment_category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroInversionesFinCat',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='FinancialInvestments',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('month', models.IntegerField(blank=True, choices=[('', '-- Seleccione Mes --'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], db_column='Mes', null=True)),
                ('amount_initial', models.DecimalField(blank=True, db_column='MontoInicial', decimal_places=2, max_digits=23, null=True)),
                ('amount_increase', models.DecimalField(blank=True, db_column='MontoAumento', decimal_places=2, max_digits=23, null=True)),
                ('amount_decrease', models.DecimalField(blank=True, db_column='MontoDisminucion', decimal_places=2, max_digits=23, null=True)),
                ('new_amount', models.DecimalField(blank=True, db_column='MontoNuevo', decimal_places=2, max_digits=23, null=True)),
                ('rate', models.FloatField(blank=True, db_column='Tasa', null=True)),
                ('amount_interest_earned', models.DecimalField(blank=True, db_column='MontoInteresGanado', decimal_places=2, max_digits=23, null=True)),
                ('amount_accounts_receivable', models.DecimalField(blank=True, db_column='MontoCuentasPorCobrar', decimal_places=2, max_digits=23, null=True)),
                ('comment', models.CharField(blank=True, db_column='Comentario', max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('scenario_id', models.ForeignKey(blank=True, db_column='EscenarioId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loan_portfolio.FinancialInvestmentsScenario')),
                ('updated_by', models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_upd_financial_investment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroInversionesFin',
                'default_permissions': [],
            },
        ),
    ]
