# Generated by Django 3.0.10 on 2021-10-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_portfolio', '0010_auto_20211012_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_april',
            field=models.FloatField(blank=True, db_column='PlazoAbr', null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_august',
            field=models.FloatField(blank=True, db_column='PlazoAgo', null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_december',
            field=models.FloatField(blank=True, db_column='PlazoDic', null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_february',
            field=models.FloatField(blank=True, db_column='PlazoFeb', null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_january',
            field=models.FloatField(blank=True, db_column='PlazoEne', null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_july',
            field=models.FloatField(blank=True, db_column='PlazoJul', null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_june',
            field=models.FloatField(blank=True, db_column='PlazoJun', null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_march',
            field=models.FloatField(blank=True, db_column='PlazoMar', null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_may',
            field=models.FloatField(blank=True, db_column='PlazoMay', null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_november',
            field=models.FloatField(blank=True, db_column='PlazoNov', null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_october',
            field=models.FloatField(blank=True, db_column='PlazoOct', null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_september',
            field=models.FloatField(blank=True, db_column='PlazoSep', null=True),
        ),
    ]
