# Generated by Django 3.0.10 on 2021-10-13 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_manejodeviaticos_categoria'),
        ('loan_portfolio', '0011_auto_20211012_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='period_id',
            field=models.ForeignKey(blank=True, db_column='PeriodoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Periodo'),
        ),
    ]
