# Generated by Django 3.0.10 on 2021-10-13 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan_portfolio', '0012_auto_20211013_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPortfolioCategoryMap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, db_column='CodigoPrestamo', null=True)),
                ('name', models.CharField(blank=True, db_column='NombrePrestamo', max_length=100, null=True)),
                ('category_id', models.ForeignKey(blank=True, db_column='CategoryId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loan_portfolio.LoanPortfolioCategory')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_update_loan_portfolio_category_map', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroCarteraCredCatTipoPrestamos',
                'default_permissions': [],
            },
        ),
    ]
