# Generated by Django 3.0.10 on 2021-10-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_portfolio', '0013_loanportfoliocategorymap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanportfoliocategorymap',
            name='category_id',
            field=models.ForeignKey(blank=True, db_column='CategoriaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loan_portfolio.LoanPortfolioCategory'),
        ),
    ]
