# Generated by Django 3.0.10 on 2021-10-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_portfolio', '0014_auto_20211013_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='commission_percentage_april',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionAbr', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='commission_percentage_august',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionAgo', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='commission_percentage_december',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionDic', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='commission_percentage_february',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionFeb', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='commission_percentage_january',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionEne', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='commission_percentage_july',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionJul', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='commission_percentage_june',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionJun', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='commission_percentage_march',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionMar', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='commission_percentage_may',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionMay', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='commission_percentage_november',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionNov', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='commission_percentage_october',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionOct', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='commission_percentage_september',
            field=models.FloatField(blank=True, db_column='PorcentajeComisionSep', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='growth_percentage_april',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoAbr', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='growth_percentage_august',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoAgo', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='growth_percentage_december',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoDic', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='growth_percentage_february',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoFeb', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='growth_percentage_january',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoEne', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='growth_percentage_july',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoJul', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='growth_percentage_june',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoJun', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='growth_percentage_march',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoMar', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='growth_percentage_may',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoMay', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='growth_percentage_november',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoNov', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='growth_percentage_october',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoOct', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='growth_percentage_september',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimientoSep', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_april',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraAbr', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_august',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraAgo', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_december',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraDic', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_february',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraFeb', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_january',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraEne', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_july',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraJul', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_june',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraJun', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_march',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraMar', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_may',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraMay', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_november',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraNov', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_october',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraOct', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='percentage_arrears_september',
            field=models.FloatField(blank=True, db_column='PorcentajeMoraSep', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='rate_april',
            field=models.FloatField(blank=True, db_column='TasaAbr', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='rate_august',
            field=models.FloatField(blank=True, db_column='TasaAgo', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='rate_december',
            field=models.FloatField(blank=True, db_column='TasaDic', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='rate_february',
            field=models.FloatField(blank=True, db_column='TasaFeb', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='rate_january',
            field=models.FloatField(blank=True, db_column='TasaEne', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='rate_july',
            field=models.FloatField(blank=True, db_column='TasaJul', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='rate_june',
            field=models.FloatField(blank=True, db_column='TasaJun', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='rate_march',
            field=models.FloatField(blank=True, db_column='TasaMar', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='rate_may',
            field=models.FloatField(blank=True, db_column='TasaMay', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='rate_november',
            field=models.FloatField(blank=True, db_column='TasaNov', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='rate_october',
            field=models.FloatField(blank=True, db_column='TasaOct', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='rate_september',
            field=models.FloatField(blank=True, db_column='TasaSep', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_april',
            field=models.FloatField(blank=True, db_column='PlazoAbr', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_august',
            field=models.FloatField(blank=True, db_column='PlazoAgo', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_december',
            field=models.FloatField(blank=True, db_column='PlazoDic', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_february',
            field=models.FloatField(blank=True, db_column='PlazoFeb', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_january',
            field=models.FloatField(blank=True, db_column='PlazoEne', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_july',
            field=models.FloatField(blank=True, db_column='PlazoJul', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_june',
            field=models.FloatField(blank=True, db_column='PlazoJun', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_march',
            field=models.FloatField(blank=True, db_column='PlazoMar', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_may',
            field=models.FloatField(blank=True, db_column='PlazoMay', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_november',
            field=models.FloatField(blank=True, db_column='PlazoNov', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_october',
            field=models.FloatField(blank=True, db_column='PlazoOct', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolioscenario',
            name='term_september',
            field=models.FloatField(blank=True, db_column='PlazoSep', default=0, null=True),
        ),
    ]
