# Generated by Django 3.0.10 on 2021-10-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_portfolio', '0015_auto_20211015_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanportfolio',
            name='amount_arrears',
            field=models.DecimalField(blank=True, db_column='MontoMora', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolio',
            name='amount_growth',
            field=models.DecimalField(blank=True, db_column='MontoCrecimiento', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolio',
            name='amount_initial',
            field=models.DecimalField(blank=True, db_column='MontoInicial', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolio',
            name='commission_amount',
            field=models.DecimalField(blank=True, db_column='MontoComision', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolio',
            name='commission_percentage',
            field=models.FloatField(blank=True, db_column='PorcentajeComision', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolio',
            name='default_interest',
            field=models.DecimalField(blank=True, db_column='InteresesMoratorios', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolio',
            name='level_quota',
            field=models.DecimalField(blank=True, db_column='CuotaNivelada', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolio',
            name='new_amount',
            field=models.DecimalField(blank=True, db_column='MontoNuevo', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolio',
            name='percent_growth',
            field=models.FloatField(blank=True, db_column='PorcentajeCrecimiento', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolio',
            name='percentage_arrears',
            field=models.FloatField(blank=True, db_column='PorcentajeMora', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolio',
            name='principal_payments',
            field=models.DecimalField(blank=True, db_column='PagosCapital', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolio',
            name='rate',
            field=models.FloatField(blank=True, db_column='Tasa', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolio',
            name='term',
            field=models.IntegerField(blank=True, db_column='Plazo', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loanportfolio',
            name='total_interest',
            field=models.DecimalField(blank=True, db_column='InteresesTotales', decimal_places=2, default=0, max_digits=23, null=True),
        ),
    ]
