# Generated by Django 3.0.10 on 2021-10-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_portfolio', '0016_auto_20211015_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='deleted',
            field=models.BooleanField(blank=True, db_column='Eliminado', default=True, null=True),
        ),
    ]
