# Generated by Django 3.0.10 on 2021-10-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_portfolio', '0018_auto_20211020_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='deleted',
            field=models.BooleanField(blank=True, db_column='Eliminado', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='financialinvestments',
            name='amount_decrease',
            field=models.DecimalField(blank=True, db_column='MontoDisminucion', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='financialinvestments',
            name='amount_increase',
            field=models.DecimalField(blank=True, db_column='MontoAumento', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='financialinvestments',
            name='amount_initial',
            field=models.DecimalField(blank=True, db_column='MontoInicial', decimal_places=2, default=0, max_digits=23, null=True),
        ),
    ]
