# Generated by Django 3.0.10 on 2021-10-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_portfolio', '0019_auto_20211020_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='base_amount',
            field=models.DecimalField(blank=True, db_column='MontoBase', decimal_places=2, max_digits=23, null=True),
        ),
    ]
