# Generated by Django 3.0.10 on 2021-10-20 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_portfolio', '0020_financialinvestmentsscenario_base_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinvestmentsscenario',
            name='category_id',
            field=models.ForeignKey(db_column='CategoriaId', on_delete=django.db.models.deletion.DO_NOTHING, to='loan_portfolio.FinancialInvestmentsCategory'),
        ),
    ]
