# Generated by Django 3.0.10 on 2021-10-20 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_manejodeviaticos_categoria'),
        ('master_budget', '0006_masterparameters_deleted'),
        ('loan_portfolio', '0021_auto_20211020_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinvestmentsscenario',
            name='parameter_id',
            field=models.ForeignKey(blank=True, db_column='ParametroId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_budget.MasterParameters'),
        ),
        migrations.AlterField(
            model_name='financialinvestmentsscenario',
            name='period_id',
            field=models.ForeignKey(blank=True, db_column='PeriodoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Periodo'),
        ),
    ]
