# Generated by Django 3.0.10 on 2021-10-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_portfolio', '0024_auto_20211020_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='rate_april',
            field=models.FloatField(blank=True, db_column='TasaAbr', default=0, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='rate_august',
            field=models.FloatField(blank=True, db_column='TasaAgo', default=0, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='rate_december',
            field=models.FloatField(blank=True, db_column='TasaDic', default=0, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='rate_february',
            field=models.FloatField(blank=True, db_column='TasaFeb', default=0, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='rate_january',
            field=models.FloatField(blank=True, db_column='TasaEne', default=0, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='rate_july',
            field=models.FloatField(blank=True, db_column='TasaJul', default=0, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='rate_june',
            field=models.FloatField(blank=True, db_column='TasaJun', default=0, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='rate_march',
            field=models.FloatField(blank=True, db_column='TasaMar', default=0, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='rate_may',
            field=models.FloatField(blank=True, db_column='TasaMay', default=0, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='rate_november',
            field=models.FloatField(blank=True, db_column='TasaNov', default=0, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='rate_october',
            field=models.FloatField(blank=True, db_column='TasaOct', default=0, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='rate_september',
            field=models.FloatField(blank=True, db_column='TasaSep', default=0, null=True),
        ),
    ]
