# Generated by Django 3.0.10 on 2021-10-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_portfolio', '0026_auto_20211025_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanportfoliocategory',
            name='code_core',
            field=models.IntegerField(blank=True, db_column='CodigoCategoria', null=True),
        ),
    ]
