# Generated by Django 3.0.10 on 2021-10-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_portfolio', '0027_loanportfoliocategory_code_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='amount_accounts_receivable_april',
            field=models.DecimalField(blank=True, db_column='CuentasXCobrarAbr', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='amount_accounts_receivable_august',
            field=models.DecimalField(blank=True, db_column='CuentasXCobrarAgo', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='amount_accounts_receivable_december',
            field=models.DecimalField(blank=True, db_column='CuentasXCobrarDic', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='amount_accounts_receivable_february',
            field=models.DecimalField(blank=True, db_column='CuentasXCobrarFeb', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='amount_accounts_receivable_january',
            field=models.DecimalField(blank=True, db_column='CuentasXCobrarEne', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='amount_accounts_receivable_july',
            field=models.DecimalField(blank=True, db_column='CuentasXCobrarJul', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='amount_accounts_receivable_june',
            field=models.DecimalField(blank=True, db_column='CuentasXCobrarJun', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='amount_accounts_receivable_march',
            field=models.DecimalField(blank=True, db_column='CuentasXCobrarMar', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='amount_accounts_receivable_may',
            field=models.DecimalField(blank=True, db_column='CuentasXCobrarsMay', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='amount_accounts_receivable_november',
            field=models.DecimalField(blank=True, db_column='CuentasXCobrarNov', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='amount_accounts_receivable_october',
            field=models.DecimalField(blank=True, db_column='CuentasXCobrarOct', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='financialinvestmentsscenario',
            name='amount_accounts_receivable_september',
            field=models.DecimalField(blank=True, db_column='CuentasXCobrarSep', decimal_places=2, default=0, max_digits=23, null=True),
        ),
    ]
