# Generated by Django 3.0.10 on 2022-02-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_portfolio', '0028_auto_20211026_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='amount_adjustment_april',
            field=models.DecimalField(blank=True, db_column='MontoAjusteCrecimientoAbr', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='amount_adjustment_august',
            field=models.DecimalField(blank=True, db_column='MontoAjusteCrecimientoAgo', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='amount_adjustment_december',
            field=models.DecimalField(blank=True, db_column='MontoAjusteCrecimientoDic', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='amount_adjustment_february',
            field=models.DecimalField(blank=True, db_column='MontoAjusteCrecimientoFeb', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='amount_adjustment_january',
            field=models.DecimalField(blank=True, db_column='MontoAjusteCrecimientoEne', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='amount_adjustment_july',
            field=models.DecimalField(blank=True, db_column='MontoAjusteCrecimientoJul', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='amount_adjustment_june',
            field=models.DecimalField(blank=True, db_column='MontoAjusteCrecimientoJun', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='amount_adjustment_march',
            field=models.DecimalField(blank=True, db_column='MontoAjusteCrecimientoMar', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='amount_adjustment_may',
            field=models.DecimalField(blank=True, db_column='MontoAjusteCrecimientoMay', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='amount_adjustment_november',
            field=models.DecimalField(blank=True, db_column='MontoAjusteCrecimientoNov', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='amount_adjustment_october',
            field=models.DecimalField(blank=True, db_column='MontoAjusteCrecimientoOct', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='amount_adjustment_september',
            field=models.DecimalField(blank=True, db_column='MontoAjusteCrecimientoSep', decimal_places=2, default=0, max_digits=23, null=True),
        ),
    ]
