# Generated by Django 3.0.10 on 2022-08-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_portfolio', '0029_auto_20220221_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanportfolio',
            name='interest_due_amount',
            field=models.DecimalField(blank=True, db_column='MontoInteresesVencidos', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolio',
            name='percantage_interest_due',
            field=models.FloatField(blank=True, db_column='PorcentajeInteresesVencidos', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolio',
            name='recovery_amount',
            field=models.DecimalField(blank=True, db_column='MontoRecuperacion', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolio',
            name='recovery_percentage',
            field=models.FloatField(blank=True, db_column='ProcentajeRecuperacion', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_of_interest_due_april',
            field=models.FloatField(blank=True, db_column='PorcentajeInteresesVencidosAbr', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_of_interest_due_august',
            field=models.FloatField(blank=True, db_column='PorcentajeInteresesVencidosAgo', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_of_interest_due_december',
            field=models.FloatField(blank=True, db_column='PorcentajeInteresesVencidosDic', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_of_interest_due_february',
            field=models.FloatField(blank=True, db_column='PorcentajeInteresesVencidosFeb', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_of_interest_due_january',
            field=models.FloatField(blank=True, db_column='PorcentajeInteresesVencidosEne', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_of_interest_due_july',
            field=models.FloatField(blank=True, db_column='PorcentajeInteresesVencidosJul', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_of_interest_due_june',
            field=models.FloatField(blank=True, db_column='PorcentajeInteresesVencidosJun', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_of_interest_due_march',
            field=models.FloatField(blank=True, db_column='PorcentajeInteresesVencidosMar', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_of_interest_due_may',
            field=models.FloatField(blank=True, db_column='PorcentajeInteresesVencidosMay', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_of_interest_due_november',
            field=models.FloatField(blank=True, db_column='PorcentajeInteresesVencidosNov', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_of_interest_due_october',
            field=models.FloatField(blank=True, db_column='PorcentajeInteresesVencidosOct', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='percentage_of_interest_due_september',
            field=models.FloatField(blank=True, db_column='PorcentajeInteresesVencidosSep', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='recovery_percentage_april',
            field=models.FloatField(blank=True, db_column='PorcentajeRecuperacionAbr', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='recovery_percentage_august',
            field=models.FloatField(blank=True, db_column='PorcentajeRecuperacionAgo', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='recovery_percentage_december',
            field=models.FloatField(blank=True, db_column='PorcentajeRecuperacionDic', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='recovery_percentage_february',
            field=models.FloatField(blank=True, db_column='PorcentajeRecuperacionFeb', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='recovery_percentage_january',
            field=models.FloatField(blank=True, db_column='PorcentajeRecuperacionEne', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='recovery_percentage_july',
            field=models.FloatField(blank=True, db_column='PorcentajeRecuperacionJul', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='recovery_percentage_june',
            field=models.FloatField(blank=True, db_column='PorcentajeRecuperacionJun', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='recovery_percentage_march',
            field=models.FloatField(blank=True, db_column='PorcentajeRecuperacionMar', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='recovery_percentage_may',
            field=models.FloatField(blank=True, db_column='PorcentajeRecuperacionMay', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='recovery_percentage_november',
            field=models.FloatField(blank=True, db_column='PorcentajeRecuperacionNov', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='recovery_percentage_october',
            field=models.FloatField(blank=True, db_column='PorcentajeRecuperacionOct', default=0, null=True),
        ),
        migrations.AddField(
            model_name='loanportfolioscenario',
            name='recovery_percentage_september',
            field=models.FloatField(blank=True, db_column='PorcentajeRecuperacionSep', default=0, null=True),
        ),
    ]
