# Generated by Django 3.0.10 on 2021-12-01 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_budget', '0006_masterparameters_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_manejodeviaticos_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPayrollScenario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('percentage_increase_january', models.FloatField(blank=True, db_column='PorcentajeincrementoEne', default=0, null=True)),
                ('percentage_increase_february', models.FloatField(blank=True, db_column='PorcentajeincrementoFeb', default=0, null=True)),
                ('percentage_increase_march', models.FloatField(blank=True, db_column='PorcentajeincrementoMar', default=0, null=True)),
                ('percentage_increase_april', models.FloatField(blank=True, db_column='PorcentajeincrementoAbr', default=0, null=True)),
                ('percentage_increase_may', models.FloatField(blank=True, db_column='PorcentajeincrementoMay', default=0, null=True)),
                ('percentage_increase_june', models.FloatField(blank=True, db_column='PorcentajeincrementoJun', default=0, null=True)),
                ('percentage_increase_july', models.FloatField(blank=True, db_column='PorcentajeincrementoJul', default=0, null=True)),
                ('percentage_increase_august', models.FloatField(blank=True, db_column='PorcentajeincrementoAgo', default=0, null=True)),
                ('percentage_increase_september', models.FloatField(blank=True, db_column='PorcentajeincrementoSep', default=0, null=True)),
                ('percentage_increase_october', models.FloatField(blank=True, db_column='PorcentajeincrementoOct', default=0, null=True)),
                ('percentage_increase_november', models.FloatField(blank=True, db_column='PorcentajeincrementoNov', default=0, null=True)),
                ('percentage_increase_december', models.FloatField(blank=True, db_column='PorcentajeincrementoDic', default=0, null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('correlative', models.CharField(blank=True, db_column='Correlativo', max_length=50, null=True)),
                ('comment', models.CharField(blank=True, db_column='Comentario', max_length=500, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='Estado', default=True, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Eliminado', default=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('parameter_id', models.ForeignKey(db_column='ParametroId', on_delete=django.db.models.deletion.DO_NOTHING, to='master_budget.MasterParameters')),
                ('period_id', models.ForeignKey(blank=True, db_column='PeriodoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Periodo')),
                ('updated_by', models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_upd_payment_payroll_scenario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroPagoPlanillaEsc',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='PaymentPayroll',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('month', models.IntegerField(blank=True, choices=[('', '-- Seleccione Mes --'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], db_column='Mes', null=True)),
                ('amount_initial_permanent', models.DecimalField(blank=True, db_column='MontoInicialPermanente', decimal_places=2, default=0, max_digits=23, null=True)),
                ('amount_initial_temp', models.DecimalField(blank=True, db_column='MontoInicialTemporal', decimal_places=2, default=0, max_digits=23, null=True)),
                ('total_amount_initial', models.DecimalField(blank=True, db_column='TotalMontoInicial', decimal_places=2, default=0, max_digits=23, null=True)),
                ('total_amount_with_increases', models.DecimalField(blank=True, db_column='TotalMontoConCrecimiento', decimal_places=2, default=0, max_digits=23, null=True)),
                ('total_amount_new_hires_permanent', models.DecimalField(blank=True, db_column='TotalMontoNuevasContratacionesPerm', decimal_places=2, default=0, max_digits=23, null=True)),
                ('total_amount_new_hires_temp', models.DecimalField(blank=True, db_column='TotalMontoNuevasContratacionesTemp', decimal_places=2, default=0, max_digits=23, null=True)),
                ('cost_center_id', models.ForeignKey(blank=True, db_column='CentroCostoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Centroscosto')),
                ('scenario_id', models.ForeignKey(blank=True, db_column='EscenarioId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment_payroll.PaymentPayrollScenario')),
            ],
            options={
                'db_table': 'pptoMaestroPagoPlanilla',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='BudgetedPaymentPayroll',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('budgeted_id', models.ForeignKey(blank=True, db_column='PersonalPresupuestadoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Detallexpresupuestopersonal')),
                ('scenario_id', models.ForeignKey(blank=True, db_column='EscenarioId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment_payroll.PaymentPayrollScenario')),
            ],
            options={
                'db_table': 'pptoMaestroPersonalPresupuestados',
                'default_permissions': [],
            },
        ),
    ]
