# Generated by Django 3.0.10 on 2021-12-02 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_manejodeviaticos_categoria'),
        ('payment_payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentpayroll',
            name='amount_initial_permanent',
        ),
        migrations.RemoveField(
            model_name='paymentpayroll',
            name='amount_initial_temp',
        ),
        migrations.RemoveField(
            model_name='paymentpayroll',
            name='total_amount_initial',
        ),
        migrations.CreateModel(
            name='PaymentPayrollMonthlySalary',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('amount_initial_permanent', models.DecimalField(blank=True, db_column='MontoInicialPermanente', decimal_places=2, default=0, max_digits=23, null=True)),
                ('amount_initial_temp', models.DecimalField(blank=True, db_column='MontoInicialTemporal', decimal_places=2, default=0, max_digits=23, null=True)),
                ('total_amount_initial', models.DecimalField(blank=True, db_column='TotalMontoInicial', decimal_places=2, default=0, max_digits=23, null=True)),
                ('cost_center_id', models.ForeignKey(blank=True, db_column='CentroCostoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Centroscosto')),
                ('scenario_id', models.ForeignKey(blank=True, db_column='EscenarioId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment_payroll.PaymentPayrollScenario')),
            ],
            options={
                'db_table': 'pptoMaestroPagoPlanillaSalario',
                'default_permissions': [],
            },
        ),
    ]
