# Generated by Django 3.0.10 on 2021-12-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_payroll', '0002_auto_20211202_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentpayrollmonthlysalary',
            name='amount_initial_permanent',
        ),
        migrations.RemoveField(
            model_name='paymentpayrollmonthlysalary',
            name='total_amount_initial',
        ),
        migrations.AddField(
            model_name='paymentpayrollmonthlysalary',
            name='adjusted_permanent_amount',
            field=models.DecimalField(blank=True, db_column='MontoPermanenteAjustado', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayrollmonthlysalary',
            name='permanent_amount_initial',
            field=models.DecimalField(blank=True, db_column='MontoPermanenteInicial', decimal_places=2, default=0, max_digits=23, null=True),
        ),
    ]
