# Generated by Django 3.0.10 on 2021-12-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_payroll', '0004_auto_20211203_1104'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basepaymentpayroll',
            table='pptoMaestroPagoPlanillaSalarioBase',
        ),
    ]
