# Generated by Django 3.0.10 on 2021-12-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_payroll', '0005_auto_20211203_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentpayroll',
            name='month',
        ),
        migrations.RemoveField(
            model_name='paymentpayroll',
            name='total_amount_new_hires_permanent',
        ),
        migrations.RemoveField(
            model_name='paymentpayroll',
            name='total_amount_new_hires_temp',
        ),
        migrations.RemoveField(
            model_name='paymentpayroll',
            name='total_amount_with_increases',
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_april',
            field=models.DecimalField(blank=True, db_column='MontoAbr', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_august',
            field=models.DecimalField(blank=True, db_column='MontoAgo', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_december',
            field=models.DecimalField(blank=True, db_column='MontoDic', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_february',
            field=models.DecimalField(blank=True, db_column='MontoFeb', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_january',
            field=models.DecimalField(blank=True, db_column='MontoEne', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_july',
            field=models.DecimalField(blank=True, db_column='MontoJul', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_june',
            field=models.DecimalField(blank=True, db_column='MontoJun', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_march',
            field=models.DecimalField(blank=True, db_column='MontoMar', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_may',
            field=models.DecimalField(blank=True, db_column='MontoMay', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_november',
            field=models.DecimalField(blank=True, db_column='MontoNov', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_october',
            field=models.DecimalField(blank=True, db_column='MontoOct', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_september',
            field=models.DecimalField(blank=True, db_column='MontoSep', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_temp_april',
            field=models.DecimalField(blank=True, db_column='MontoTemporalAbr', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_temp_august',
            field=models.DecimalField(blank=True, db_column='MontoTemporalAgo', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_temp_december',
            field=models.DecimalField(blank=True, db_column='MontoTemporalDic', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_temp_february',
            field=models.DecimalField(blank=True, db_column='MontoTemporalFeb', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_temp_january',
            field=models.DecimalField(blank=True, db_column='MontoTemporalEne', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_temp_july',
            field=models.DecimalField(blank=True, db_column='MontoTemporalJul', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_temp_june',
            field=models.DecimalField(blank=True, db_column='MontoTemporalJun', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_temp_march',
            field=models.DecimalField(blank=True, db_column='MontoTemporalMar', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_temp_may',
            field=models.DecimalField(blank=True, db_column='MontoTemporalMay', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_temp_november',
            field=models.DecimalField(blank=True, db_column='MontoTemporalNov', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_temp_october',
            field=models.DecimalField(blank=True, db_column='MontoTemporalOct', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_temp_september',
            field=models.DecimalField(blank=True, db_column='MontoTemporalSep', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='percentage_increase_april',
            field=models.FloatField(blank=True, db_column='PorcentajeincrementoAbr', default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='percentage_increase_august',
            field=models.FloatField(blank=True, db_column='PorcentajeincrementoAgo', default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='percentage_increase_december',
            field=models.FloatField(blank=True, db_column='PorcentajeincrementoDic', default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='percentage_increase_february',
            field=models.FloatField(blank=True, db_column='PorcentajeincrementoFeb', default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='percentage_increase_january',
            field=models.FloatField(blank=True, db_column='PorcentajeincrementoEne', default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='percentage_increase_july',
            field=models.FloatField(blank=True, db_column='PorcentajeincrementoJul', default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='percentage_increase_june',
            field=models.FloatField(blank=True, db_column='PorcentajeincrementoJun', default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='percentage_increase_march',
            field=models.FloatField(blank=True, db_column='PorcentajeincrementoMar', default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='percentage_increase_may',
            field=models.FloatField(blank=True, db_column='PorcentajeincrementoMay', default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='percentage_increase_november',
            field=models.FloatField(blank=True, db_column='PorcentajeincrementoNov', default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='percentage_increase_october',
            field=models.FloatField(blank=True, db_column='PorcentajeincrementoOct', default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='percentage_increase_september',
            field=models.FloatField(blank=True, db_column='PorcentajeincrementoSep', default=0, null=True),
        ),
    ]
