# Generated by Django 3.0.10 on 2021-12-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_payroll', '0006_auto_20211205_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpayroll',
            name='adjusted_permanent_amount',
            field=models.DecimalField(blank=True, db_column='MontoPermanenteAjustado', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='amount_initial_temp',
            field=models.DecimalField(blank=True, db_column='MontoInicialTemporal', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayroll',
            name='permanent_amount_initial',
            field=models.DecimalField(blank=True, db_column='MontoPermanenteInicial', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.DeleteModel(
            name='BasePaymentPayroll',
        ),
    ]
