# Generated by Django 3.0.10 on 2022-01-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_manejodeviaticos_categoria'),
        ('payment_payroll', '0008_auto_20211207_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalleteralPayrollCatalog',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, db_column='Valor', default=0, null=True)),
                ('counter', models.IntegerField(blank=True, db_column='Contador', default=0, null=True)),
                ('type', models.CharField(blank=True, db_column='Tipo', default='', max_length=5, null=True)),
                ('account_id', models.ForeignKey(blank=True, db_column='CuentaContableId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Cuentascontables')),
            ],
            options={
                'db_table': 'pptoMaestroPagoPlanillaColateralesCatalog',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='CalleteralPayroll',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, db_column='Valor', default=0, null=True)),
                ('catalog_id', models.ForeignKey(blank=True, db_column='ColateralesCatalogoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment_payroll.CalleteralPayrollCatalog')),
                ('scenario_id', models.ForeignKey(blank=True, db_column='EscenarioId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment_payroll.PaymentPayrollScenario')),
            ],
            options={
                'db_table': 'pptoMaestroPagoPlanillaColaterales',
                'default_permissions': [],
            },
        ),
    ]
