# Generated by Django 3.0.10 on 2022-01-06 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_payroll', '0009_calleteralpayroll_calleteralpayrollcatalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calleteralpayrollcatalog',
            name='account_id',
        ),
        migrations.AddField(
            model_name='paymentpayrollscenario',
            name='holidays',
            field=models.FloatField(blank=True, db_column='DiasVacaciones', default=0, null=True),
        ),
        migrations.AddField(
            model_name='paymentpayrollscenario',
            name='percentage_labor_coverage',
            field=models.FloatField(blank=True, db_column='PorcentajeCoberturaLaboral', default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='paymentpayrollscenario',
            name='percentage_plan_sac',
            field=models.FloatField(blank=True, db_column='PorcentajePlanSAC', default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='paymentpayrollscenario',
            name='percentage_rap',
            field=models.FloatField(blank=True, db_column='PorcentajeRAP', default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='paymentpayrollscenario',
            name='percentage_social_security',
            field=models.FloatField(blank=True, db_column='PorcentajeSeguroSocial', default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='paymentpayrollscenario',
            name='percentage_special_bonuses',
            field=models.FloatField(blank=True, db_column='PorcentajeBonificacionesEspeciales', default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.DeleteModel(
            name='CalleteralPayroll',
        ),
        migrations.DeleteModel(
            name='CalleteralPayrollCatalog',
        ),
    ]
