# Generated by Django 3.0.10 on 2022-05-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_payroll', '0010_auto_20220106_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentpayroll',
            name='amount_april',
            field=models.DecimalField(blank=True, db_column='MontoAbr', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='paymentpayroll',
            name='amount_august',
            field=models.DecimalField(blank=True, db_column='MontoAgo', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='paymentpayroll',
            name='amount_december',
            field=models.DecimalField(blank=True, db_column='MontoDic', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='paymentpayroll',
            name='amount_february',
            field=models.DecimalField(blank=True, db_column='MontoFeb', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='paymentpayroll',
            name='amount_january',
            field=models.DecimalField(blank=True, db_column='MontoEne', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='paymentpayroll',
            name='amount_july',
            field=models.DecimalField(blank=True, db_column='MontoJul', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='paymentpayroll',
            name='amount_june',
            field=models.DecimalField(blank=True, db_column='MontoJun', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='paymentpayroll',
            name='amount_march',
            field=models.DecimalField(blank=True, db_column='MontoMar', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='paymentpayroll',
            name='amount_may',
            field=models.DecimalField(blank=True, db_column='MontoMay', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='paymentpayroll',
            name='amount_november',
            field=models.DecimalField(blank=True, db_column='MontoNov', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='paymentpayroll',
            name='amount_october',
            field=models.DecimalField(blank=True, db_column='MontoOct', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='paymentpayroll',
            name='amount_september',
            field=models.DecimalField(blank=True, db_column='MontoSep', decimal_places=4, default=0, max_digits=23, null=True),
        ),
    ]
