# Generated by Django 3.0.10 on 2022-07-30 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0008_auto_20220308_2016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_budget', '0013_auto_20220304_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityScenario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('correlative', models.CharField(blank=True, db_column='Correlativo', max_length=50, null=True)),
                ('comment', models.CharField(blank=True, db_column='Comentario', max_length=500, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='Estado', default=True, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Eliminado', default=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('parameter_id', models.ForeignKey(db_column='ParametroId', on_delete=django.db.models.deletion.DO_NOTHING, to='master_budget.MasterParameters')),
                ('period_id', models.ForeignKey(blank=True, db_column='PeriodoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Periodo')),
                ('updated_by', models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_upd_equity_scenario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroPatrimonioEsc',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='EquityCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='Estado', default=True, null=True)),
                ('identifier', models.CharField(blank=True, db_column='Identificador', max_length=150, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_update_equity_category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroPatrimonioCat',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('increases_january', models.DecimalField(blank=True, db_column='AumentoEne', decimal_places=2, default=0, max_digits=23, null=True)),
                ('increases_february', models.DecimalField(blank=True, db_column='AumentoFeb', decimal_places=2, default=0, max_digits=23, null=True)),
                ('increases_march', models.DecimalField(blank=True, db_column='AumentoMar', decimal_places=2, default=0, max_digits=23, null=True)),
                ('increases_april', models.DecimalField(blank=True, db_column='AumentoAbr', decimal_places=2, default=0, max_digits=23, null=True)),
                ('increases_may', models.DecimalField(blank=True, db_column='AumentoMay', decimal_places=2, default=0, max_digits=23, null=True)),
                ('increases_june', models.DecimalField(blank=True, db_column='AumentoJun', decimal_places=2, default=0, max_digits=23, null=True)),
                ('increases_july', models.DecimalField(blank=True, db_column='AumentoJul', decimal_places=2, default=0, max_digits=23, null=True)),
                ('increases_august', models.DecimalField(blank=True, db_column='AumentoAgo', decimal_places=2, default=0, max_digits=23, null=True)),
                ('increases_september', models.DecimalField(blank=True, db_column='AumentoSep', decimal_places=2, default=0, max_digits=23, null=True)),
                ('increases_october', models.DecimalField(blank=True, db_column='AumentoOct', decimal_places=2, default=0, max_digits=23, null=True)),
                ('increases_november', models.DecimalField(blank=True, db_column='AumentoNov', decimal_places=2, default=0, max_digits=23, null=True)),
                ('increases_december', models.DecimalField(blank=True, db_column='AumentoDic', decimal_places=2, default=0, max_digits=23, null=True)),
                ('amount_january', models.DecimalField(blank=True, db_column='MontoEne', decimal_places=4, default=0, max_digits=23, null=True)),
                ('amount_february', models.DecimalField(blank=True, db_column='MontoFeb', decimal_places=4, default=0, max_digits=23, null=True)),
                ('amount_march', models.DecimalField(blank=True, db_column='MontoMar', decimal_places=4, default=0, max_digits=23, null=True)),
                ('amount_april', models.DecimalField(blank=True, db_column='MontoAbr', decimal_places=4, default=0, max_digits=23, null=True)),
                ('amount_may', models.DecimalField(blank=True, db_column='MontoMay', decimal_places=4, default=0, max_digits=23, null=True)),
                ('amount_june', models.DecimalField(blank=True, db_column='MontoJun', decimal_places=4, default=0, max_digits=23, null=True)),
                ('amount_july', models.DecimalField(blank=True, db_column='MontoJul', decimal_places=4, default=0, max_digits=23, null=True)),
                ('amount_august', models.DecimalField(blank=True, db_column='MontoAgo', decimal_places=4, default=0, max_digits=23, null=True)),
                ('amount_september', models.DecimalField(blank=True, db_column='MontoSep', decimal_places=4, default=0, max_digits=23, null=True)),
                ('amount_october', models.DecimalField(blank=True, db_column='MontoOct', decimal_places=4, default=0, max_digits=23, null=True)),
                ('amount_november', models.DecimalField(blank=True, db_column='MontoNov', decimal_places=4, default=0, max_digits=23, null=True)),
                ('amount_december', models.DecimalField(blank=True, db_column='MontoDic', decimal_places=4, default=0, max_digits=23, null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('category', models.IntegerField(blank=True, db_column='Categoria', null=True)),
                ('category_name', models.CharField(blank=True, db_column='CategoriaNombre', max_length=150, null=True)),
                ('previous_balance', models.DecimalField(blank=True, db_column='SaldoAnterior', decimal_places=2, default=0, max_digits=23, null=True)),
                ('criteria', models.IntegerField(blank=True, choices=[(1, 'Mismo Valor'), (2, 'Porcentaje de Aumento'), (3, 'Porcentaje de Disminución'), (4, 'Nuevo Valor')], db_column='Criterio', null=True)),
                ('comment', models.CharField(blank=True, db_column='Comentario', default='', max_length=200, null=True)),
                ('percentage', models.FloatField(blank=True, db_column='Procentaje', default=0, null=True)),
                ('new_balance', models.DecimalField(blank=True, db_column='NuevoSaldo', decimal_places=2, default=0, max_digits=23, null=True)),
                ('category_id', models.ForeignKey(blank=True, db_column='CategoriaId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patrimony.EquityCategory')),
                ('scenario_id', models.ForeignKey(blank=True, db_column='EscenarioId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patrimony.EquityScenario')),
            ],
            options={
                'db_table': 'pptoMaestroPatrimonio',
                'default_permissions': [],
            },
        ),
    ]
