# Generated by Django 3.0.10 on 2022-08-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220308_2016'),
        ('patrimony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution_surplus_period',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('surplus_amount', models.DecimalField(db_column='MontoExcedentes', decimal_places=2, default=0, max_digits=18)),
                ('id_period', models.ForeignKey(db_column='IdPeriodo', on_delete=django.db.models.deletion.DO_NOTHING, to='main.Periodo')),
            ],
            options={
                'db_table': 'pptoMaestroDistribucionExcedentesPeriodo',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Surplus_category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Nombre', max_length=100)),
                ('order', models.IntegerField(db_column='Orden')),
                ('action', models.CharField(db_column='Accion', max_length=5)),
            ],
            options={
                'db_table': 'pptoMaestroCategoriaExcedentes',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='DistributionSurplus_category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Etiqueta', max_length=100)),
                ('percentage', models.FloatField(db_column='Porcentaje', default=0)),
                ('amount', models.DecimalField(db_column='Monto', decimal_places=2, default=0, max_digits=18)),
                ('id_dsp', models.ForeignKey(db_column='IdDEP', on_delete=django.db.models.deletion.DO_NOTHING, to='patrimony.Distribution_surplus_period')),
                ('id_surplus_category', models.ForeignKey(db_column='IdCategoriaExcedentes', on_delete=django.db.models.deletion.DO_NOTHING, to='patrimony.Surplus_category')),
            ],
            options={
                'db_table': 'pptoMaestroDistribucionExcedentesCategoria',
                'default_permissions': [],
            },
        ),
    ]
