# Generated by Django 3.0.10 on 2022-08-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimony', '0003_auto_20220819_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributionsurplusperiod',
            old_name='id_period',
            new_name='period_id',
        ),
    ]
