# Generated by Django 3.0.10 on 2022-08-20 09:27

import apps.master_budget.patrimony.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimony', '0004_auto_20220819_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionsurpluscategory',
            name='percentage',
            field=models.FloatField(db_column='Porcentaje', default=0, validators=[apps.master_budget.patrimony.models.is_percentage]),
        ),
    ]
