FINANCIAL_INVESTMENT = [
    {"name": "Normales", "is_active": True, "identifier": "1"},
    {"name": "FEC", "is_active": True, "identifier": "2"},
]


SAVINGS_LIABILITIES_CATEGORY = [
    {
        "name": "Aportaciones",
        "is_active": True,
        "identifier": "EXEC sp_pptoMaestroAhorrosAportacionesObtenerSaldoHist @ParametroId =",  # NOQA
    },
    {
        "name": "Ahorros Retirables",
        "is_active": True,
        "identifier": "EXEC sp_pptoMaestroAhorrosRetirableObtenerSaldoHist @ParametroId =",  # NOQA
    },
    {
        "name": "Previcoop",
        "is_active": True,
        "identifier": "EXEC sp_pptoMaestroAhorrosPrevicoopObtenerSaldoHist @ParametroId =",  # NOQA
    },
    {
        "name": "Ahorros CDT",
        "is_active": True,
        "identifier": "EXEC sp_pptoMaestroAhorrosCdtObtenerSaldoHist @ParametroId =",
    },
]


LIABILITIES_LOANS_CATEGORY = [
    {"name": "RAP", "is_active": True, "identifier": "1"},
    {"name": "BANHPROVI", "is_active": True, "identifier": "2"},
    {"name": "BCH", "is_active": True, "identifier": "3"},
    {"name": "BCIE", "is_active": True, "identifier": "4"},
]

NON_PERFORMING_ASSETS_CATEGORY = [
    {"name": "TERRENOS", "is_active": True, "identifier": "1"},
    {"name": "EDIFICIOS", "is_active": True, "identifier": "2"},
    {"name": "INSTALACIONES", "is_active": True, "identifier": "3"},
    {"name": "MUEB. Y EQ.", "is_active": True, "identifier": "4"},
    {"name": "VEHICULOS", "is_active": True, "identifier": "5"},
    {"name": "SOFTWARE", "is_active": True, "identifier": "6"},
]

NON_PERFORMING_ASSETS_CATEGORY_PER_ACCOUNTS = [
    {"account_id": "19529", "category_identifier": "2"},
    {"account_id": "18931", "category_identifier": "3"},
    {"account_id": "833", "category_identifier": "3"},
    {"account_id": "18934", "category_identifier": "4"},
    {"account_id": "18932", "category_identifier": "4"},
    {"account_id": "18933", "category_identifier": "4"},
    {"account_id": "835", "category_identifier": "4"},
    {"account_id": "18935", "category_identifier": "4"},
    {"account_id": "834", "category_identifier": "5"},
    {"account_id": "19539", "category_identifier": "6"},
]

OTHERS_ASSETS_CATEGORY = [
    {
        "name": "Otros Activos",
        "is_active": True,
        "identifier": "EXEC [dbo].[sp_pptoMaestroBienesCapitalActivosOtrosActivosObtenerSaldoHist] @ParametroId = ",  # NOQA
    },
    {
        "name": "Activos Eventuales",
        "is_active": True,
        "identifier": "EXEC [dbo].[sp_pptoMaestroBienesCapitalActivosEventualesObtenerSaldoHist] @ParametroId = ",  # NOQA
    },
    {
        "name": "Cargos Diferidos",
        "is_active": True,
        "identifier": "EXEC [dbo].[sp_pptoMaestroBienesCapitalActivosCargosDiferidosObtenerSaldoHist] @ParametroId = ",  # NOQA
    },
    {
        "name": "Activos Monetarios",
        "is_active": True,
        "identifier": "EXEC [dbo].[sp_pptoMaestroBienesCapitalActivosMonetariosObtenerSaldoHist] @ParametroId = ",  # NOQA
    },
]

CATALOG_LOSSE____S_EARNINGS = [
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Nacional",
        "level_three": "Otros Productos Financieros M/N",
        "level_four": "Fluctuaciones Tipo de Cambio",
        "order": 9,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Ingresos Intereses Inversiones M/E",
        "level_four": "Intereses sobre Depositos Cheques y Ahorros",
        "order": 10,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Ingresos Intereses Inversiones M/E",
        "level_four": "Intereses sobre Inversiones ( CDP )",
        "order": 11,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses S/Prestamos Fiduciarios",
        "order": 12,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses S/Prestamos Automaticos",
        "order": 13,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses S/Prestamos Prendarios",
        "order": 14,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses S/Prestamos Hipotecarios",
        "order": 15,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses S/Prestamos Garantia Mixta",
        "order": 16,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses S/Prestamos Refinanciados",
        "order": 17,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses S/Prestamos Readecuados",
        "order": 18,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses Moratorios S/Cartera",
        "order": 19,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Emergencia Covi-19",
        "order": 20,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Productos por Servicios",
        "level_three": "Productos por Servicios",
        "level_four": "Comisiones Western Union",
        "order": 21,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Productos por Servicios",
        "level_three": "Productos por Servicios",
        "level_four": "Comision Recoleccion Hondutel",
        "order": 22,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Productos por Servicios",
        "level_three": "Productos por Servicios",
        "level_four": "Comision Colegiaturas",
        "order": 23,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Productos por Servicios",
        "level_three": "Productos por Servicios",
        "level_four": "Recoleccion de Agua",
        "order": 24,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Productos por Servicios",
        "level_three": "Productos por Servicios",
        "level_four": "5% Ventas de Timbre COHPUCP",
        "order": 25,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Productos por Servicios",
        "level_three": "Productos por Servicios",
        "level_four": "Recoleccion Junta Agua LOLO",
        "order": 26,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otras Comisiones",
        "level_three": "Otras Comisiones",
        "level_four": "Comision de recargas Tigo",
        "order": 27,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otras Comisiones",
        "level_three": "Otras Comisiones",
        "level_four": "Comision de recargas Claro",
        "order": 28,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otras Comisiones",
        "level_three": "Otras Comisiones",
        "level_four": "Comision Venta Productos Claro",
        "order": 29,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otras Comisiones",
        "level_three": "Otras Comisiones",
        "level_four": "Comisión de Tarjeta Debicoop- BAC",
        "order": 30,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otras Comisiones",
        "level_three": "Otras Comisiones",
        "level_four": "Otros Ingresos por Tarjetas de Debito",
        "order": 31,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otras Comisiones",
        "level_three": "Otras Comisiones",
        "level_four": "Comisiones por Tarjetas de Credito M/N",
        "order": 32,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otros Ingresos por Servicios",
        "level_three": "Otros Ingresos por Servicios",
        "level_four": "Otros Ingresos por Servicios",
        "order": 33,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otros Productos",
        "level_three": "Otros Productos",
        "level_four": "Venta de Activos Eventuales",
        "order": 34,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otros Productos",
        "level_three": "Otros Productos",
        "level_four": "Venta de Bienes Muebles e Inmuebles",
        "order": 35,
    },
    {
        "type": "G",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otros Productos",
        "level_three": "Otros Productos",
        "level_four": "Ingreso por Cartera Castigada",
        "order": 36,
    },


    {
        "type": "P",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos Financieros",
        "level_three": "Comisiones Pagadas M/N",
        "level_four": "Otras Comisiones",
        "order": 41,
    },
    {
        "type": "P",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos Financieros",
        "level_three": "Otros Gastos",
        "level_four": "Fluctuacion Tipo de cambio",
        "order": 42,
    },
    {
        "type": "P",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos Financieros",
        "level_three": "Intereses sobre Cartera Depositaria M/E",
        "level_four": "Intereses Pagados Depositos de Ahorro",
        "order": 43,
    },
    {
        "type": "P",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos Financieros",
        "level_three": "Intereses sobre Cartera Depositaria M/E",
        "level_four": "Intereses Pagados Depositos a Plazo",
        "order": 44,
    },
]


CATALOG_LOSSES_EARNINGS = [
    {
        "type": "G",
        "method": "A",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Nacional",
        "level_three": "Ingresos Intereses Inversiones M/N",
        "level_four": "Intereses sobre Depositos Cheques y Ahorros",
        "order": 1,
    },
    {
        "type": "G",
        "method": "A",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Nacional",
        "level_three": "Ingresos Intereses Inversiones M/N",
        "level_four": "Intereses sobre Inversiones ( CDP )",
        "order": 2,
    },
    {
        "type": "G",
        "method": "A",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Nacional",
        "level_three": "Intereses sobre Cartera Prestamos M/N",
        "level_four": "Intereses S/Prestamos Fiduciarios",
        "order": 3,
    },
    {
        "type": "G",
        "method": "A",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Nacional",
        "level_three": "Intereses sobre Cartera Prestamos M/N",
        "level_four": "Intereses S/Prestamos Automaticos",
        "order": 4,
    },
    {
        "type": "G",
        "method": "A",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Nacional",
        "level_three": "Intereses sobre Cartera Prestamos M/N",
        "level_four": "Intereses S/Prestamos Hipotecarios",
        "order": 5,
    },
    {
        "type": "G",
        "method": "A",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Nacional",
        "level_three": "Intereses sobre Cartera Prestamos M/N",
        "level_four": "Intereses S/Ptmos.Fondos Redescontados",
        "order": 6,
    },
    {
        "type": "G",
        "method": "A",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Nacional",
        "level_three": "Intereses sobre Cartera Prestamos M/N",
        "level_four": "Otros",
        "order": 7,
    },
    {
        "type": "G",
        "method": "A",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Nacional",
        "level_three": "Comisiones M/N",
        "level_four": "Comisiones Devengadas",
        "order": 8,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Nacional",
        "level_three": "Otros Productos Financieros M/N",
        "level_four": "Fluctuaciones Tipo de Cambio",
        "order": 9,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Ingresos Intereses Inversiones M/E",
        "level_four": "Intereses sobre Depositos Cheques y Ahorros",
        "order": 10,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Ingresos Intereses Inversiones M/E",
        "level_four": "Intereses sobre Inversiones ( CDP )",
        "order": 11,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses S/Prestamos Fiduciarios",
        "order": 12,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses S/Prestamos Automaticos",
        "order": 13,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses S/Prestamos Prendarios",
        "order": 14,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses S/Prestamos Hipotecarios",
        "order": 15,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses S/Prestamos Garantia Mixta",
        "order": 16,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses S/Prestamos Refinanciados",
        "order": 17,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses S/Prestamos Readecuados",
        "order": 18,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Intereses Moratorios S/Cartera",
        "order": 19,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Ingresos Moneda Extranjera",
        "level_three": "Intereses sobre Cartera Prestamos M/E",
        "level_four": "Emergencia Covi-19",
        "order": 20,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Productos por Servicios",
        "level_three": "Productos por Servicios",
        "level_four": "Comisiones Western Union",
        "order": 21,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Productos por Servicios",
        "level_three": "Productos por Servicios",
        "level_four": "Comision Recoleccion Hondutel",
        "order": 22,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Productos por Servicios",
        "level_three": "Productos por Servicios",
        "level_four": "Comision Colegiaturas",
        "order": 23,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Productos por Servicios",
        "level_three": "Productos por Servicios",
        "level_four": "Recoleccion de Agua",
        "order": 24,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Productos por Servicios",
        "level_three": "Productos por Servicios",
        "level_four": "5% Ventas de Timbre COHPUCP",
        "order": 25,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Productos por Servicios",
        "level_three": "Productos por Servicios",
        "level_four": "Recoleccion Junta Agua LOLO",
        "order": 26,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otras Comisiones",
        "level_three": "Otras Comisiones",
        "level_four": "Comision de recargas Tigo",
        "order": 27,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otras Comisiones",
        "level_three": "Otras Comisiones",
        "level_four": "Comision de recargas Claro",
        "order": 28,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otras Comisiones",
        "level_three": "Otras Comisiones",
        "level_four": "Comision Venta Productos Claro",
        "order": 29,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otras Comisiones",
        "level_three": "Otras Comisiones",
        "level_four": "Comisión de Tarjeta Debicoop- BAC",
        "order": 30,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otras Comisiones",
        "level_three": "Otras Comisiones",
        "level_four": "Otros Ingresos por Tarjetas de Debito",
        "order": 31,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otras Comisiones",
        "level_three": "Otras Comisiones",
        "level_four": "Comisiones por Tarjetas de Credito M/N",
        "order": 32,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otros Ingresos por Servicios",
        "level_three": "Otros Ingresos por Servicios",
        "level_four": "Otros Ingresos por Servicios",
        "order": 33,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otros Productos",
        "level_three": "Otros Productos",
        "level_four": "Venta de Activos Eventuales",
        "order": 34,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otros Productos",
        "level_three": "Otros Productos",
        "level_four": "Venta de Bienes Muebles e Inmuebles",
        "order": 35,
    },
    {
        "type": "G",
        "method": "M",
        "level_one": "INGRESOS TOTALES",
        "level_two": "Otros Productos",
        "level_three": "Otros Productos",
        "level_four": "Ingreso por Cartera Castigada",
        "order": 36,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos Financieros",
        "level_three": "Intereses sobre Cartera Depositaria M/N",
        "level_four": "Intereses Pagados Depositos de Ahorro",
        "order": 37,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos Financieros",
        "level_three": "Intereses sobre Cartera Depositaria M/N",
        "level_four": "Intereses Pagados Depositos a Plazo",
        "order": 38,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos Financieros",
        "level_three": "Intereses sobre Cartera Depositaria M/N",
        "level_four": "Intereses Pagados Aportaciones",
        "order": 39,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos Financieros",
        "level_three": "Intereses pagados Sobre Prestamos Redescontados",
        "level_four": "Intereses pagados Sobre Prestamos Redescontados",
        "order": 40,
    },
    {
        "type": "P",
        "method": "M",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos Financieros",
        "level_three": "Comisiones Pagadas M/N",
        "level_four": "Otras Comisiones",
        "order": 41,
    },
    {
        "type": "P",
        "method": "M",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos Financieros",
        "level_three": "Otros Gastos",
        "level_four": "Fluctuacion Tipo de cambio",
        "order": 42,
    },
    {
        "type": "P",
        "method": "M",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos Financieros",
        "level_three": "Intereses sobre Cartera Depositaria M/E",
        "level_four": "Intereses Pagados Depositos de Ahorro",
        "order": 43,
    },
    {
        "type": "P",
        "method": "M",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos Financieros",
        "level_three": "Intereses sobre Cartera Depositaria M/E",
        "level_four": "Intereses Pagados Depositos a Plazo",
        "order": 44,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos de Administracion y Generales",
        "level_three": "Directivos",
        "level_four": "Directivos",
        "order": 45,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos de Administracion y Generales",
        "level_three": "Funcionarios y Empleados",
        "level_four": "Funcionarios y Empleados",
        "order": 46,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos de Administracion y Generales",
        "level_three": "Impuestos y Contribuciones",
        "level_four": "Impuestos y Contribuciones",
        "order": 47,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos de Administracion y Generales",
        "level_three": "Honorarios Profesionales",
        "level_four": "Honorarios Profesionales",
        "order": 48,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos de Administracion y Generales",
        "level_three": "Arrendamientos",
        "level_four": "Arrendamientos",
        "order": 49,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos de Administracion y Generales",
        "level_three": "Reparacion, Uso y Mantenimiento",
        "level_four": "Reparacion, Uso y Mantenimiento",
        "order": 50,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos de Administracion y Generales",
        "level_three": "Seguridad y Vigilancia",
        "level_four": "Seguridad y Vigilancia",
        "order": 51,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos de Administracion y Generales",
        "level_three": "Actividades de Mercadeo",
        "level_four": "Actividades de Mercadeo",
        "order": 52,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos de Administracion y Generales",
        "level_three": "Amortizacion de Primas de Seguro",
        "level_four": "Amortizacion de Primas de Seguro",
        "order": 53,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos de Administracion y Generales",
        "level_three": "Depreciaciones y Amortizaciones",
        "level_four": "Depreciaciones",
        "order": 54,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos de Administracion y Generales",
        "level_three": "Depreciaciones y Amortizaciones",
        "level_four": "Provisiones Rva.Ctas Incobrables",
        "order": 55,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos de Administracion y Generales",
        "level_three": "Depreciaciones y Amortizaciones",
        "level_four": "Reservas Activos Eventuales",
        "order": 56,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos de Administracion y Generales",
        "level_three": "Papeleria, Utiles y Suministros",
        "level_four": "Papeleria, Utiles y Suministros",
        "order": 57,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos de Administracion y Generales",
        "level_three": "Gastos Diversos",
        "level_four": "Gastos Diversos",
        "order": 58,
    },
    {
        "type": "P",
        "method": "A",
        "level_one": "CUENTAS DE GASTOS",
        "level_two": "Gastos de Administracion y Generales",
        "level_three": "Otros Gastos",
        "level_four": "Otros Gastos",
        "order": 59,
    },
    {
        "type": "E",
        "method": "A",
        "level_one": "EXCEDENTES",
        "level_two": "EXCEDENTES",
        "level_three": "EXCEDENTES",
        "level_four": "EXCEDENTES",
        "order": 100,
    },
]
