# Generated by Django 3.0.10 on 2021-10-29 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsLiabilities',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('month', models.IntegerField(blank=True, choices=[('', '-- Seleccione Mes --'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], db_column='Mes', null=True)),
                ('amount_initial', models.DecimalField(blank=True, db_column='MontoInicial', decimal_places=2, default=0, max_digits=23, null=True)),
                ('percent_growth', models.FloatField(blank=True, db_column='PorcentajeCrecimiento', default=0, null=True)),
                ('amount_growth', models.DecimalField(blank=True, db_column='MontoCrecimiento', decimal_places=2, default=0, max_digits=23, null=True)),
                ('new_amount', models.DecimalField(blank=True, db_column='MontoTotalCrecimiento', decimal_places=2, default=0, max_digits=23, null=True)),
                ('rate', models.FloatField(blank=True, db_column='Tasa', default=0, null=True)),
                ('total_interest', models.DecimalField(blank=True, db_column='InteresesGenerado', decimal_places=2, default=0, max_digits=23, null=True)),
                ('comment', models.CharField(blank=True, db_column='Comentario', max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('scenario_id', models.ForeignKey(blank=True, db_column='EscenarioId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='passives.SavingsLiabilitiesScenario')),
                ('updated_by', models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_upd_savings_liabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroPasivoAhorro',
                'default_permissions': [],
            },
        ),
    ]
