# Generated by Django 3.0.10 on 2021-10-29 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_budget', '0006_masterparameters_deleted'),
        ('main', '0007_manejodeviaticos_categoria'),
        ('passives', '0002_savingsliabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiabilitiesLoansCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='Estado', default=True, null=True)),
                ('identifier', models.CharField(blank=True, db_column='Identificador', max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_update_liabilities_loans_category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroPasivoPrestamosCat',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='LiabilitiesLoansScenario',
            fields=[
                ('growth_percentage_january', models.FloatField(blank=True, db_column='PorcentajeCrecimientoEne', default=0, null=True)),
                ('growth_percentage_february', models.FloatField(blank=True, db_column='PorcentajeCrecimientoFeb', default=0, null=True)),
                ('growth_percentage_march', models.FloatField(blank=True, db_column='PorcentajeCrecimientoMar', default=0, null=True)),
                ('growth_percentage_april', models.FloatField(blank=True, db_column='PorcentajeCrecimientoAbr', default=0, null=True)),
                ('growth_percentage_may', models.FloatField(blank=True, db_column='PorcentajeCrecimientoMay', default=0, null=True)),
                ('growth_percentage_june', models.FloatField(blank=True, db_column='PorcentajeCrecimientoJun', default=0, null=True)),
                ('growth_percentage_july', models.FloatField(blank=True, db_column='PorcentajeCrecimientoJul', default=0, null=True)),
                ('growth_percentage_august', models.FloatField(blank=True, db_column='PorcentajeCrecimientoAgo', default=0, null=True)),
                ('growth_percentage_september', models.FloatField(blank=True, db_column='PorcentajeCrecimientoSep', default=0, null=True)),
                ('growth_percentage_october', models.FloatField(blank=True, db_column='PorcentajeCrecimientoOct', default=0, null=True)),
                ('growth_percentage_november', models.FloatField(blank=True, db_column='PorcentajeCrecimientoNov', default=0, null=True)),
                ('growth_percentage_december', models.FloatField(blank=True, db_column='PorcentajeCrecimientoDic', default=0, null=True)),
                ('rate_january', models.FloatField(blank=True, db_column='TasaEne', default=0, null=True)),
                ('rate_february', models.FloatField(blank=True, db_column='TasaFeb', default=0, null=True)),
                ('rate_march', models.FloatField(blank=True, db_column='TasaMar', default=0, null=True)),
                ('rate_april', models.FloatField(blank=True, db_column='TasaAbr', default=0, null=True)),
                ('rate_may', models.FloatField(blank=True, db_column='TasaMay', default=0, null=True)),
                ('rate_june', models.FloatField(blank=True, db_column='TasaJun', default=0, null=True)),
                ('rate_july', models.FloatField(blank=True, db_column='TasaJul', default=0, null=True)),
                ('rate_august', models.FloatField(blank=True, db_column='TasaAgo', default=0, null=True)),
                ('rate_september', models.FloatField(blank=True, db_column='TasaSep', default=0, null=True)),
                ('rate_october', models.FloatField(blank=True, db_column='TasaOct', default=0, null=True)),
                ('rate_november', models.FloatField(blank=True, db_column='TasaNov', default=0, null=True)),
                ('rate_december', models.FloatField(blank=True, db_column='TasaDic', default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('correlative', models.CharField(blank=True, db_column='Correlativo', max_length=50, null=True)),
                ('comment', models.CharField(blank=True, db_column='Comentario', max_length=500, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='Estado', default=True, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Eliminado', default=False, null=True)),
                ('base_amount', models.DecimalField(blank=True, db_column='MontoBase', decimal_places=2, max_digits=23, null=True)),
                ('annual_growth_amount', models.DecimalField(blank=True, db_column='MontoCrecimientoAnual', decimal_places=2, max_digits=23, null=True)),
                ('category_id', models.ForeignKey(db_column='CategoriaId', on_delete=django.db.models.deletion.DO_NOTHING, to='passives.LiabilitiesLoansCategory')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('parameter_id', models.ForeignKey(db_column='ParametroId', on_delete=django.db.models.deletion.DO_NOTHING, to='master_budget.MasterParameters')),
                ('period_id', models.ForeignKey(blank=True, db_column='PeriodoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Periodo')),
                ('updated_by', models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_upd_liabilities_loans_scenario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroPasivoPrestamossc',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='LiabilitiesLoansComment',
            fields=[
                ('comment', models.CharField(blank=True, db_column='Comentario', max_length=500, null=True)),
                ('deleted', models.BooleanField(blank=True, db_column='Borrado', default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('scenario_id', models.ForeignKey(blank=True, db_column='EscenarioId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='passives.LiabilitiesLoansScenario')),
            ],
            options={
                'db_table': 'pptoMaestroPasivoPrestamosMsj',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='LiabilitiesLoans',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='FechaActualizacion', null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('month', models.IntegerField(blank=True, choices=[('', '-- Seleccione Mes --'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], db_column='Mes', null=True)),
                ('amount_initial', models.DecimalField(blank=True, db_column='MontoInicial', decimal_places=2, default=0, max_digits=23, null=True)),
                ('percent_growth', models.FloatField(blank=True, db_column='PorcentajeCrecimiento', default=0, null=True)),
                ('amount_growth', models.DecimalField(blank=True, db_column='MontoCrecimiento', decimal_places=2, default=0, max_digits=23, null=True)),
                ('principal_payments', models.DecimalField(blank=True, db_column='PagosCapital', decimal_places=2, default=0, max_digits=23, null=True)),
                ('new_amount', models.DecimalField(blank=True, db_column='MontoTotalCrecimiento', decimal_places=2, default=0, max_digits=23, null=True)),
                ('rate', models.FloatField(blank=True, db_column='Tasa', default=0, null=True)),
                ('level_quota', models.DecimalField(blank=True, db_column='CuotaNivelada', decimal_places=2, default=0, max_digits=23, null=True)),
                ('total_interest', models.DecimalField(blank=True, db_column='InteresesPagados', decimal_places=2, default=0, max_digits=23, null=True)),
                ('comment', models.CharField(blank=True, db_column='Comentario', max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('scenario_id', models.ForeignKey(blank=True, db_column='EscenarioId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='passives.LiabilitiesLoansScenario')),
                ('updated_by', models.ForeignKey(blank=True, db_column='ActualizadoPor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_upd_liabilities_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pptoMaestroPasivoPrestamos',
                'default_permissions': [],
            },
        ),
    ]
