# Generated by Django 3.0.10 on 2021-11-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0003_liabilitiesloans_liabilitiesloanscategory_liabilitiesloanscomment_liabilitiesloansscenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsliabilitiescategory',
            name='identifier',
            field=models.CharField(blank=True, db_column='Identificador', max_length=150, null=True),
        ),
    ]
