# Generated by Django 3.0.10 on 2021-11-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0004_auto_20211104_0832'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='liabilitiesloansscenario',
            table='pptoMaestroPasivoPrestamosEsc',
        ),
    ]
