# Generated by Django 3.0.10 on 2021-11-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passives', '0005_auto_20211108_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='liabilitiesloansscenario',
            name='term_april',
            field=models.FloatField(blank=True, db_column='PlazoAbr', default=0, null=True),
        ),
        migrations.AddField(
            model_name='liabilitiesloansscenario',
            name='term_august',
            field=models.FloatField(blank=True, db_column='PlazoAgo', default=0, null=True),
        ),
        migrations.AddField(
            model_name='liabilitiesloansscenario',
            name='term_december',
            field=models.FloatField(blank=True, db_column='PlazoDic', default=0, null=True),
        ),
        migrations.AddField(
            model_name='liabilitiesloansscenario',
            name='term_february',
            field=models.FloatField(blank=True, db_column='PlazoFeb', default=0, null=True),
        ),
        migrations.AddField(
            model_name='liabilitiesloansscenario',
            name='term_january',
            field=models.FloatField(blank=True, db_column='PlazoEne', default=0, null=True),
        ),
        migrations.AddField(
            model_name='liabilitiesloansscenario',
            name='term_july',
            field=models.FloatField(blank=True, db_column='PlazoJul', default=0, null=True),
        ),
        migrations.AddField(
            model_name='liabilitiesloansscenario',
            name='term_june',
            field=models.FloatField(blank=True, db_column='PlazoJun', default=0, null=True),
        ),
        migrations.AddField(
            model_name='liabilitiesloansscenario',
            name='term_march',
            field=models.FloatField(blank=True, db_column='PlazoMar', default=0, null=True),
        ),
        migrations.AddField(
            model_name='liabilitiesloansscenario',
            name='term_may',
            field=models.FloatField(blank=True, db_column='PlazoMay', default=0, null=True),
        ),
        migrations.AddField(
            model_name='liabilitiesloansscenario',
            name='term_november',
            field=models.FloatField(blank=True, db_column='PlazoNov', default=0, null=True),
        ),
        migrations.AddField(
            model_name='liabilitiesloansscenario',
            name='term_october',
            field=models.FloatField(blank=True, db_column='PlazoOct', default=0, null=True),
        ),
        migrations.AddField(
            model_name='liabilitiesloansscenario',
            name='term_september',
            field=models.FloatField(blank=True, db_column='PlazoSep', default=0, null=True),
        ),
    ]
