# Generated by Django 3.0.10 on 2021-09-22 13:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_inversiones_meses_depreciacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='responsablesporcentroscostos',
            unique_together={('CodCentroCosto', 'CodUser')},
        ),
    ]
