# Generated by Django 3.0.10 on 2021-10-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210922_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centroscosto',
            options={'ordering': ('desccentrocosto',)},
        ),
        migrations.AlterModelOptions(
            name='cuentascontables',
            options={'ordering': ('desccuentacontable',)},
        ),
        migrations.AlterModelOptions(
            name='inversiones',
            options={'ordering': ('descinversion',)},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ('-descperiodo', '-fechalimite')},
        ),
        migrations.AlterModelOptions(
            name='proyectos',
            options={'ordering': ('-fechainicio', 'descproyecto', 'codcentrocosto')},
        ),
        migrations.AlterModelOptions(
            name='responsablesporcentroscostos',
            options={'ordering': ('CodCentroCosto', 'CodUser', 'Estado')},
        ),
        migrations.AddField(
            model_name='detallexpresupuestoinversion',
            name='monto_depreciacion_anual',
            field=models.DecimalField(blank=True, db_column='MontoDepreciacionAnual', decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='detallexpresupuestoinversion',
            name='monto_depreciacion_mensual',
            field=models.DecimalField(blank=True, db_column='MontoDepreciacionMensual', decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='detallexpresupuestoinversion',
            name='numero_meses',
            field=models.IntegerField(blank=True, db_column='NumeroMeses', null=True),
        ),
    ]
