# Generated by Django 3.0.10 on 2021-10-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211003_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallexpresupuestoinversion',
            name='numero_meses_depreciacion',
            field=models.IntegerField(blank=True, db_column='NumeroMesesDepreciacion', null=True),
        ),
    ]
