# Generated by Django 3.0.10 on 2021-10-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211004_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='manejodeviaticos',
            name='categoria',
            field=models.CharField(blank=True, db_column='categoria', max_length=2, null=True),
        ),
    ]
