# Generated by Django 3.0.10 on 2022-03-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_manejodeviaticos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='centroscosto',
            name='code_zone',
            field=models.IntegerField(blank=True, db_column='CodZona', null=True),
        ),
        migrations.AddField(
            model_name='centroscosto',
            name='zone',
            field=models.CharField(blank=True, db_column='Zona', max_length=50, null=True),
        ),
    ]
