# Generated by Django 3.0.10 on 2022-03-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='globalgoaldetail',
            table='MetasGlobalDetalle',
        ),
    ]
