# Generated by Django 3.0.10 on 2022-03-08 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_manejodeviaticos_categoria'),
        ('goals', '0002_auto_20220304_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalgoalperiod',
            name='period_id',
            field=models.OneToOneField(blank=True, db_column='PeriodoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Periodo'),
        ),
    ]
