# Generated by Django 3.0.10 on 2022-03-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20220308_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='manual_definition',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='manual_execution',
        ),
        migrations.AddField(
            model_name='goal',
            name='definition',
            field=models.CharField(blank=True, db_column='Definicion', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='execution',
            field=models.CharField(blank=True, db_column='Ejecucion', max_length=1, null=True),
        ),
    ]
