# Generated by Django 3.0.10 on 2022-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_auto_20220308_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='definition',
            field=models.CharField(blank=True, choices=[('A', 'Automaticas'), ('M', 'Manuales')], db_column='Definicion', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='execution',
            field=models.CharField(blank=True, choices=[('A', 'Automaticas'), ('M', 'Manuales')], db_column='Ejecucion', max_length=1, null=True),
        ),
    ]
