# Generated by Django 3.0.10 on 2022-03-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_auto_20220310_0902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='globalgoaldetail',
            unique_together={('id_global_goal_period', 'id_goal')},
        ),
    ]
