# Generated by Django 3.0.10 on 2022-03-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_auto_20220310_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='definition',
            field=models.CharField(blank=True, choices=[('A', 'Automaticas'), ('M', 'Manuales')], db_column='Definicion', default='M', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='execution',
            field=models.CharField(blank=True, choices=[('A', 'Automaticas'), ('M', 'Manuales')], db_column='Ejecucion', default='M', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='type',
            field=models.CharField(blank=True, choices=[('A', 'Automaticas'), ('S', 'Semi Automaticas'), ('M', 'Manuales')], db_column='Tipo', default='M', max_length=1, null=True),
        ),
    ]
