# Generated by Django 3.0.10 on 2022-03-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_subsidiarygoaldetail_id_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiarygoaldetail',
            name='id_goal',
            field=models.ForeignKey(db_column='IdMetas', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='goals.Goal'),
        ),
    ]
