# Generated by Django 3.0.10 on 2022-03-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_subsidiarygoaldetail_id_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiarygoaldetail',
            name='id_global_goal_detail',
            field=models.ForeignKey(db_column='IdMetaGlobal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='goals.GlobalGoalDetail'),
        ),
    ]
