# Generated by Django 3.0.10 on 2022-03-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220308_2016'),
        ('goals', '0010_subsidiarygoaldetail_id_global_goal_detail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subsidiarygoaldetail',
            unique_together={('id_global_goal_period', 'id_goal', 'id_cost_center')},
        ),
    ]
