# Generated by Django 3.0.10 on 2022-03-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0011_auto_20220318_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_april',
            field=models.DecimalField(blank=True, db_column='MontoEjecucionAbr', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_august',
            field=models.DecimalField(blank=True, db_column='MontoEjecucionAgo', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_december',
            field=models.DecimalField(blank=True, db_column='MontoEjecucionDic', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_february',
            field=models.DecimalField(blank=True, db_column='MontoEjecucionFeb', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_january',
            field=models.DecimalField(blank=True, db_column='MontoEjecucionEne', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_july',
            field=models.DecimalField(blank=True, db_column='MontoEjecucionJul', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_june',
            field=models.DecimalField(blank=True, db_column='MontoEjecucionJun', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_march',
            field=models.DecimalField(blank=True, db_column='MontoEjecucionMar', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_may',
            field=models.DecimalField(blank=True, db_column='MontoEjecucionMay', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_november',
            field=models.DecimalField(blank=True, db_column='MontoEjecucionNov', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_october',
            field=models.DecimalField(blank=True, db_column='MontoEjecucionOct', decimal_places=2, default=0, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_september',
            field=models.DecimalField(blank=True, db_column='MontoEjecucionSep', decimal_places=2, default=0, max_digits=23, null=True),
        ),
    ]
