# Generated by Django 3.0.10 on 2022-03-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_auto_20220328_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_april',
        ),
        migrations.RemoveField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_august',
        ),
        migrations.RemoveField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_december',
        ),
        migrations.RemoveField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_february',
        ),
        migrations.RemoveField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_january',
        ),
        migrations.RemoveField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_july',
        ),
        migrations.RemoveField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_june',
        ),
        migrations.RemoveField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_march',
        ),
        migrations.RemoveField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_may',
        ),
        migrations.RemoveField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_november',
        ),
        migrations.RemoveField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_october',
        ),
        migrations.RemoveField(
            model_name='subsidiarygoaldetail',
            name='amount_execution_september',
        ),
    ]
