# Generated by Django 3.0.10 on 2022-03-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0014_auto_20220329_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsidiarygoaldetail',
            old_name='amount_execution_april',
            new_name='amount_exec_april',
        ),
        migrations.RenameField(
            model_name='subsidiarygoaldetail',
            old_name='amount_execution_august',
            new_name='amount_exec_august',
        ),
        migrations.RenameField(
            model_name='subsidiarygoaldetail',
            old_name='amount_execution_december',
            new_name='amount_exec_december',
        ),
        migrations.RenameField(
            model_name='subsidiarygoaldetail',
            old_name='amount_execution_february',
            new_name='amount_exec_february',
        ),
        migrations.RenameField(
            model_name='subsidiarygoaldetail',
            old_name='amount_execution_january',
            new_name='amount_exec_january',
        ),
        migrations.RenameField(
            model_name='subsidiarygoaldetail',
            old_name='amount_execution_july',
            new_name='amount_exec_july',
        ),
        migrations.RenameField(
            model_name='subsidiarygoaldetail',
            old_name='amount_execution_june',
            new_name='amount_exec_june',
        ),
        migrations.RenameField(
            model_name='subsidiarygoaldetail',
            old_name='amount_execution_march',
            new_name='amount_exec_march',
        ),
        migrations.RenameField(
            model_name='subsidiarygoaldetail',
            old_name='amount_execution_may',
            new_name='amount_exec_may',
        ),
        migrations.RenameField(
            model_name='subsidiarygoaldetail',
            old_name='amount_execution_november',
            new_name='amount_exec_november',
        ),
        migrations.RenameField(
            model_name='subsidiarygoaldetail',
            old_name='amount_execution_october',
            new_name='amount_exec_october',
        ),
        migrations.RenameField(
            model_name='subsidiarygoaldetail',
            old_name='amount_execution_september',
            new_name='amount_exec_september',
        ),
    ]
