# Generated by Django 3.0.10 on 2022-05-17 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0016_goal_user_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalgoaldetail',
            name='amount_april',
            field=models.DecimalField(blank=True, db_column='MontoAbr', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='globalgoaldetail',
            name='amount_august',
            field=models.DecimalField(blank=True, db_column='MontoAgo', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='globalgoaldetail',
            name='amount_december',
            field=models.DecimalField(blank=True, db_column='MontoDic', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='globalgoaldetail',
            name='amount_february',
            field=models.DecimalField(blank=True, db_column='MontoFeb', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='globalgoaldetail',
            name='amount_january',
            field=models.DecimalField(blank=True, db_column='MontoEne', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='globalgoaldetail',
            name='amount_july',
            field=models.DecimalField(blank=True, db_column='MontoJul', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='globalgoaldetail',
            name='amount_june',
            field=models.DecimalField(blank=True, db_column='MontoJun', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='globalgoaldetail',
            name='amount_march',
            field=models.DecimalField(blank=True, db_column='MontoMar', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='globalgoaldetail',
            name='amount_may',
            field=models.DecimalField(blank=True, db_column='MontoMay', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='globalgoaldetail',
            name='amount_november',
            field=models.DecimalField(blank=True, db_column='MontoNov', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='globalgoaldetail',
            name='amount_october',
            field=models.DecimalField(blank=True, db_column='MontoOct', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='globalgoaldetail',
            name='amount_september',
            field=models.DecimalField(blank=True, db_column='MontoSep', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user_assigned',
            field=models.ForeignKey(blank=True, db_column='UsuarioAsignado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subsidiarygoaldetail',
            name='amount_april',
            field=models.DecimalField(blank=True, db_column='MontoAbr', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='subsidiarygoaldetail',
            name='amount_august',
            field=models.DecimalField(blank=True, db_column='MontoAgo', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='subsidiarygoaldetail',
            name='amount_december',
            field=models.DecimalField(blank=True, db_column='MontoDic', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='subsidiarygoaldetail',
            name='amount_february',
            field=models.DecimalField(blank=True, db_column='MontoFeb', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='subsidiarygoaldetail',
            name='amount_january',
            field=models.DecimalField(blank=True, db_column='MontoEne', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='subsidiarygoaldetail',
            name='amount_july',
            field=models.DecimalField(blank=True, db_column='MontoJul', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='subsidiarygoaldetail',
            name='amount_june',
            field=models.DecimalField(blank=True, db_column='MontoJun', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='subsidiarygoaldetail',
            name='amount_march',
            field=models.DecimalField(blank=True, db_column='MontoMar', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='subsidiarygoaldetail',
            name='amount_may',
            field=models.DecimalField(blank=True, db_column='MontoMay', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='subsidiarygoaldetail',
            name='amount_november',
            field=models.DecimalField(blank=True, db_column='MontoNov', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='subsidiarygoaldetail',
            name='amount_october',
            field=models.DecimalField(blank=True, db_column='MontoOct', decimal_places=4, default=0, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='subsidiarygoaldetail',
            name='amount_september',
            field=models.DecimalField(blank=True, db_column='MontoSep', decimal_places=4, default=0, max_digits=23, null=True),
        ),
    ]
